#!/usr/bin/env bash
mkdir -p /var/config/brinkervii/grapejuice/ 
cp -n /app/user_settings.json /var/config/brinkervii/grapejuice/     
exec /usr/bin/env PYTHONPATH="${PYTHONPATH}:/app/lib/python3.10/pip_deps" GRAPEJUICE_LOCALE_DIRECTORY=/app/share/locale python3 -m grapejuiced "$@"
