app-id: com.ml4w.hyprlandsettings
runtime: org.gnome.Platform
runtime-version: '47' # Use a recent stable GNOME Platform version
sdk: org.gnome.Sdk
command: hyprland-settings # This is the Exec command from your .desktop file

finish-args:
  - --share=ipc
  - --socket=fallback-x11 # For XWayland compatibility (e.g., if Hyprland is run via XWayland)
  - --socket=wayland       # For native Wayland support (essential for Hyprland)
  - --share=network
  - --device=dri
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=home

modules:
  - name: hyprland-settings
    buildsystem: meson
    sources:
      - type: git
        url: https://github.com/mylinuxforwork/hyprland-settings.git
        tag: master