diff --git a/Makefile b/Makefile
index 1a7ff0905..10eb6a379 100644
--- a/Makefile
+++ b/Makefile
@@ -82,7 +82,7 @@ LIPO:=$(DISTDIR)/lipo/lipo_linux_amd64
 NSIS:=makensis
 LAUNCH4J:=$(DISTDIR)/launch4j/launch4j/launch4j
 
-SKIPS:=
+SKIPS:= -Dasciidoctor.skip=true -Dspotbugs.skip=true -Dlicense.skipDownloadLicenses -Dclirr.skip=true -Dmaven.javadoc.skip=true -Dpmd.skip=true -Dmaven.test.skip=true
 
 # -Dasciidoctor.skip=true
 # -Dspotbugs.skip=true
@@ -92,14 +92,16 @@ SKIPS:=
 # -Dpmd.skip=true
 # -Dmaven.test.skip=true
 
-jar: SKIPS:=-Dasciidoctor.skip=true -Dspotbugs.skip=true -Dlicense.skipDownloadLicenses
+jar: SKIPS:=-Dasciidoctor.skip=true -Dspotbugs.skip=true -Dlicense.skipDownloadLicenses -Dmaven.test.skip=true
 jar: $(LIBDIR)/Vengine.jar
 
 compile:
-	$(MVN) compile
+#	$(MVN) compile $(SKIPS)
+	mvn -o compile $(SKIPS)
 
 version-set:
-	$(MVN) versions:set -DnewVersion=$(MAVEN_VERSION) -DgenerateBackupPoms=false
+#	$(MVN) versions:set -DnewVersion=$(MAVEN_VERSION)
+#	mvn -o versions:set -DnewVersion=$(MAVEN_VERSION)
 
 test:
 	$(MVN) test
@@ -108,7 +110,7 @@ $(TMPDIR) $(JDOCDIR):
 	mkdir -p $@
 
 $(LIBDIR)/Vengine.jar: version-set
-	$(MVN) deploy -DgitVersion=$(VERSION) -Dasciidoctor.attributes=optimize $(SKIPS)
+	mvn deploy -DgitVersion=$(VERSION) -Dasciidoctor.attributes=optimize $(SKIPS)
 	mv $(LIBDIR)/$(JARNAME).jar $@
 	mv $(LIBDIR)/vassal-agent-$(MAVEN_VERSION).jar $(LIBDIR)/vassal-agent.jar
 
@@ -197,7 +199,6 @@ $(TMPDIR)/VASSAL-$(VERSION)-other.zip: $(TMPDIR)/other-$(VERSION)-build/VASSAL-$
 
 $(TMPDIR)/linux-$(VERSION)-build/VASSAL-$(VERSION): $(LIBDIR)/Vengine.jar
 	mkdir -p $@
-	cp -a $(DOCDIR) $@/doc
 	cp -a CHANGES LICENSE README.md $@
 	cp -a $(LIBDIR) $@/lib
 	cp $(DISTDIR)/VASSAL.sh $@
