diff --git a/Makefile b/Makefile
index 2c7d33b..3314c5d 100644
--- a/Makefile
+++ b/Makefile
@@ -128,7 +128,6 @@ ifeq ($(OSTYPE),darwin)
 	@+make --silent -C dependencies -f Makefile.mac $(MAKECMDGOALS)
 endif
 ifeq ($(OSTYPE),linux)
-	@+make --silent -C dependencies -f Makefile.linux $(MAKECMDGOALS)
 endif
 ifeq ($(OSTYPE),windows)
 	@+make --silent -C dependencies -f Makefile.windows $(MAKECMDGOALS)
