#!/bin/sh

# La app está en /app/lib/jearcast/
# Los recursos están en /app/lib/jearcast/resources/
# Dentro de resources/ está app.asar que contiene el código fuente

# Cambiar al directorio de recursos
cd /app/lib/jearcast/resources/

# Ejecutar la aplicación desde la raíz, pasando la ruta al main.js dentro del ASAR
exec /app/lib/jearcast/jearcast --no-sandbox src/main.js "$@"