only-arches:
  - x86_64
build-options:
  prepend-ld-library-path: /app/lib32
  prepend-pkg-config-path: /app/lib32/pkgconfig
  # Some autotools-based builds will fail if -L/app/lib32 isn't first
  ldflags: -L/app/lib32 -Wl,-z,relro,-z,now -Wl,--as-needed
  ldflags-override: true
  libdir: /app/lib32
  arch:
    x86_64:
      append-path: /usr/lib/sdk/toolchain-i386/bin
      prepend-pkg-config-path: /usr/lib/i386-linux-gnu/pkgconfig
      env:
        CC: ccache i686-unknown-linux-gnu-gcc
        CXX: ccache i686-unknown-linux-gnu-g++
