name: mobile-config-firefox
buildsystem: simple
sources:
  - type: git
    url: https://gitlab.postmarketos.org/postmarketOS/mobile-config-firefox
    commit: aae92d26e6cac47f63f7b3dbc2d6b7ae0ce9d5ee
  - type: shell
    commands:
      - sed -i 's#/etc/mobile-config-firefox#/app/etc/mobile-config-firefox#g' src/mobile-config-autoconfig.js
build-commands:
  - make install DESTDIR=/app FIREFOX_DIR=lib/firefox FIREFOX_CONFIG_DIR=lib/firefox/distribution
  - mv /app/lib/firefox/distribution/policies/policies.json /app/lib/firefox/distribution/policies.json

