name: Deno CI

on:
  push:
    paths:
      - deno/**
    branches:
      - master
  pull_request:
    paths:
      - deno/**
    branches:
      - master

defaults:
  run:
    working-directory: deno

permissions:
  contents: read

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      # 6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Setup Deno
        # 2.0.4
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run doc linter
        run: deno doc --lint src/main.ts

      - name: Run type check
        run: deno check .

      - name: Run tests
        run: deno test -A
