#!/bin/sh
set -eu

archive=/app/extra/Hyperion-v0.1.0-linux-x64.tar.gz
destination=/app/extra/hyperion
mkdir -p "$destination"
tar -xzf "$archive" -C "$destination" --strip-components=1
chmod 0755 "$destination/Hyperion"
