#!/bin/sh

./bootstrap.sh "$@"

cat <<EOF > "Makefile"
LIB_TARGETS = --with-atomic --with-chrono --with-date_time --with-random --with-system --with-thread
all:
	./b2 -j `nproc --ignore=1` \$(LIB_TARGETS)
install:
	./b2 install \$(LIB_TARGETS)
EOF

