#!/usr/bin/env bash
# https://stackoverflow.com/questions/3144089/expand-python-search-path-to-other-source
export PYTHONPATH=$PYTHONPATH:$HOME/.var/app/org.libreoffice.LibreOffice/sandbox/lib/python3.12/site-packages:$HOME/var/app/org.libreoffice.LibreOffice/data/python/lib/python3.12/site-packages
python3 -m librepythonista_py_edit.cell_edit "$@"
