#!/usr/bin/python3

# Copyright (C) 2026 imngkhang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.fsf.org/licenses/>.

import os
import sys

# Path to AppRun inside /app/extra
CLASSIN_APPRUN = "/app/extra/opt/apps/classin/AppRun"


def main():
    # Check if executable exists after extraction (which should be done by Flatpak at install time)
    if not os.path.exists(CLASSIN_APPRUN):
        sys.stderr.write(
            f"Error: Executable not found at {CLASSIN_APPRUN}.\n"
            "Make sure 'apply_extra' completed successfully during Flatpak installation.\n"
        )
        sys.exit(1)

    cmd = [CLASSIN_APPRUN] + sys.argv[1:]

    try:
        # Replace current process directly with ClassIn executable
        os.execv(CLASSIN_APPRUN, cmd)
    except OSError as e:
        sys.stderr.write(f"Failed to execute {CLASSIN_APPRUN}: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()