app-id: com.github.tsmetana.mpk3-settings
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
finish-args:
  - --device=all
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
command: mpk3-settings
cleanup:
  - /include
  - '*.a'
  - '*.la'
modules:
  - name: mpk3-settings
    buildsystem: autotools
    post-install:
      - sed -i'' "s/desktop-id\">com.github.tsmetana.mpk3-settings/desktop-id\">com.github.tsmetana.mpk3-settings.desktop/" "pkg/${FLATPAK_ID}.metainfo.xml"
      - install -D -t /app/share/metainfo pkg/${FLATPAK_ID}.metainfo.xml
      - install -D -t /app/share/icons/hicolor/scalable/apps pkg/${FLATPAK_ID}.svg
      - install -D -t /app/share/applications pkg/${FLATPAK_ID}.desktop
    sources:
    - type: git
      url: https://github.com/tsmetana/mpk3-settings
      tag: v0.1.0
      commit: 82ef6865e5854a0b222d8e68cbce263de58629c9
    - type: script
      commands:
      - "autoreconf -i"
    modules:
    - name: rtmidi
      buildsystem: cmake-ninja
      sources:
      - type: git
        url: https://github.com/thestk/rtmidi
        tag: 6.0.0
        commit: 1e5b49925aa60065db52de44c366d446a902547b
