#!/bin/bash

##############################################################################################################################################################
# AUTOR: Paco Guerrero <fjgj1@hotmail.com> - FranjeGueje
# LICENSE: GNU General Public License v3.0 (https://github.com/FranjeGueje/DeckTools/blob/master/LICENSE)
# ABOUT: Añade imágenes de nuestros juegos steam YA DESCARGADOS a los directorios COMPATDATA y SHADERCACHE
#        Add images of our ALREADY DOWNLOADED steam games to the COMPATDATA and SHADERCACHE directories
# SALIDAS/EXITs:
#   0: Todo correcto, llegamos al final. All correct, we have reached the end.
#
##############################################################################################################################################################


#########################################
##      VARIABLES GLOBALES
#########################################
# Name of application
export NOMBRE=Deckico
# Where is the wizzard
RUTA=$(readlink -f "$(dirname "$0")")
export PATHAPP="$RUTA"
export YAD="$PATHAPP/yad"
export CLI="$PATHAPP/deckico-cli"
export IMAGES="/app/usr/share/icons/deckico"

export IMICON="$IMAGES/icon.icon"
IMDECKICO="$IMAGES/deckico.png"
IMRUN="$IMAGES/run.png"
IMUNDO="$IMAGES/undo.png"
IMINS="$IMAGES/install.png"
IMUNINS="$IMAGES/uninstall.png"

# Set language
case "$LANG" in
    es_ES.UTF-8)
        lRUN="Lanzar ahora"
        lUNDO="Deshacer cambios"
        lUNATT="Ejecución desatendida en el arranque"
        lIONBOOT="Instalar en autorranque"
        lUONBOOT="Desinstalar en autorranque"
        lDRUN="Lanza el ejecutable ahora mismo"
        lDUNDO="Deja los directorios por defecto"
        lDINS="Ejecuta Deckico en cada arranque del sistema"
        lDUNI="Desinstala Deckico del arranque"
        ;;
    *)
        lRUN="Run now"
        lUNDO="Undo changes"
        lUNATT="Unattended execution on boot"
        lIONBOOT="Install on boot"
        lUONBOOT="Uninstall on boot"
        lDRUN="Launch the executable now"
        lDUNDO="Undo changes. Directoories by default"
        lDINS="Run Deckico on every system startup"
        lDUNI="Uninstall Deckico from startup"
        ;;
esac

#########################################
##      FUNCIONES
#########################################
function runD(){
    "$CLI" && "$YAD" --window-icon="$IMICON" --title="$NOMBRE""_done" --center --width=350 --timeout=3 --on-top --no-buttons --text="Done!" --text-align=center
}
export -f runD

function undoD(){
    "$CLI" --removeicons && "$YAD" --window-icon="$IMICON" --title="$NOMBRE""_done" --center --width=350 --timeout=3 --on-top --no-buttons --text="Done!" --text-align=center
}
export -f undoD

function installD(){
    "$CLI" -i && "$YAD" --window-icon="$IMICON" --title="$NOMBRE""_done" --center --width=350 --timeout=3 --on-top --no-buttons --text="Done!" --text-align=center
}
export -f installD

function uninstallD(){
    "$CLI" -u && "$YAD" --window-icon="$IMICON" --title="$NOMBRE""_done" --center --width=350 --timeout=3 --on-top --no-buttons --text="Done!" --text-align=center
}
export -f uninstallD

"$YAD" --window-icon="$IMICON" --title="$NOMBRE" --width=250 --no-buttons --center --fixed --image="$IMDECKICO" --form \
--field="$lRUN"'!'"$IMRUN"'!'"$lDRUN":FBTN "bash -c runD" \
--field="$lUNDO"'!'"$IMUNDO"'!'"$lDUNDO":FBTN "bash -c undoD" \
--field='':RO "$lUNATT" \
--field="$lIONBOOT"'!'"$IMINS"'!'"$lDINS":FBTN "bash -c installD" \
--field="$lUONBOOT"'!'"$IMUNINS"'!'"$lDUNI":FBTN "bash -c uninstallD"

exit 0
