#!/bin/sh

start_delta() {
  exec /app/bin/deltachat-tauri "$@"
}

BYPASS_NV_CHECK= #Incase you want to skip this check

if [ -n "$BYPASS_NV_CHECK" ]; then
  start_delta
fi

is_nvidia_present=$(lspci | grep -io 'nvidia')
text_thingy=$(printf "Nvidia Card detected:\nDeltaChat tauri requires for all nvidia users to execute this command:\n\`flatpak override --user --env=WEBKIT_DISABLE_COMPOSITING_MODE=1 chat.delta.DeltaChatTauri\`")
reasoning=$(printf "Reason why this needs to be done:\nTauri on nvidia crashes due to a bug with webkit's compositing mode, due to the performance effects of disabling that mode, we have made the decision to exclude this fix by default")


if [ -n "$is_nvidia_present" ]; then
  output=$(zenity --warning --text="$text_thingy" \
  --extra-button="Why?")
  if [ -n "$output" ]; then
    zenity --info --text="$reasoning"
  fi
  exit 127
fi

start_delta
