#!/bin/bash

set -xueo pipefail
cd "$(dirname "$0")"

mkdir -p "$1"
# Duplicate output to a log file
exec &> >(tee ""$1"/flatpak-build-$(date +"%F-%H%M%S").log")

SOURCE_DIR="$2"
MANIFEST="$3"

echo "Usage: ./devbuild [LOG_DIR] [SOURCE_DIR] [MANIFEST](w/out the .yml/.yaml/.json extension)"
echo " "

flatpak uninstall --assumeyes "${MANIFEST}" ||
    echo "flatpak packages were not already installed."

/usr/bin/time -f %E \
    flatpak-builder --user --install --force-clean --keep-build-dirs "${SOURCE_DIR}/build" ""${SOURCE_DIR}"/"${MANIFEST}".yml"
