#!/bin/sh
/bin/cp -r /app/share/dunedynasty $XDG_DATA_HOME
if ! [ -f "$XDG_DATA_HOME/dunedynasty/data/DUNE.PAK" ]; then
  error="ERROR: Dune II data files not found.\nPlace your Dune2 1.07eu data files in $XDG_DATA_HOME/dunedynasty/data"
  if command -v zenity >/dev/null 2>&1; then
    zenity --error --title="Dune Dynasty" --text="$error"
  elif command -v notify-send >/dev/null 2>&1; then
    notify-send "Dune Dynasty" "$error"
  else
    echo $error
  fi
else
  /app/bin/dunedynasty
fi
