#!/usr/bin/env sh

BAMBU_STUDIO_APP_LOCALE_ERROR="An error occured while setting up locale"
BAMBU_STUDIO_APP_FALLBACK_LOCALE=en_US.UTF-8
USE_LOCALE_WORKAROUND=$( (/app/bin/bambu-studio --help 2>&1 | grep "$BAMBU_STUDIO_APP_LOCALE_ERROR") >/dev/null && echo true || echo false)

if [ $USE_LOCALE_WORKAROUND = true ]; then
    [ -n "$LANG" ] && export LC_ALL=$LANG || export LC_ALL=$BAMBU_STUDIO_APP_FALLBACK_LOCALE
    echo "Message: $(date +%T): WARN: Executing bambu-studio with locale workaround $LC_ALL"
fi

if [ $BAMBU_STUDIO_DARK_THEME == true ]; then
    export GTK_THEME='Adwaita:dark'
    # echo "Message: $(date +%T): INFO: using dark theme variant"
fi

exec /app/bin/bambu-studio "$@" &
$(/app/bin/set-dark-theme-variant.py) &
