#!/usr/bin/env sh

if [ $BAMBU_STUDIO_DARK_THEME == true ]; then
    export GTK_THEME='Adwaita:dark'
    # echo "Message: $(date +%T): INFO: using dark theme variant"
fi

exec /app/bin/bambu-studio "$@" &
$(/app/bin/set-dark-theme-variant.py) &
