#!/usr/bin/env sh

PRUSA_SLICER_APP_LOCALE_ERROR="An error occured while setting up locale"
PRUSA_SLICER_APP_FALLBACK_LOCALE=en_US.UTF-8
USE_LOCALE_WORKAROUND=$( (/app/bin/prusa-slicer --help 2>&1 | grep "$PRUSA_SLICER_APP_LOCALE_ERROR") >/dev/null && echo true || echo false)

echo "--------------------------------------------------------------------------"
echo "Message: $(date +%T): Starting PrusaSlicer flatpak with entrypoint script"
echo "--------------------------------------------------------------------------"

if [ $USE_LOCALE_WORKAROUND = true ]; then
    [ -n "$LANG" ] && export LC_ALL=$LANG || export LC_ALL=$PRUSA_SLICER_APP_FALLBACK_LOCALE
    echo "Message: $(date +%T): WARN: Executing prusa-slicer with locale workaround $LC_ALL"
fi

[ $PRUSA_SLICER_DARK_THEME == true ] &&
    export GTK_THEME='Adwaita:dark' &&
    echo "Message: $(date +%T): INFO: using dark theme variant"

exec /app/bin/prusa-slicer "$@" &
$(/app/bin/set-dark-theme-variant.py) &
