#!/bin/sh

for i in "$@"
do
  case $i in
	--module=*)
	MODULENAME="${i#*=}"
	shift
	;;
	*)
	ARGS="$ARGS $i"
	shift
	;;
  esac
done


cat <<EOF > Makefile
all:
	echo "Nothing"

install:
	mkdir /tmp/fonts
	cd /tmp/fonts
	curl -L https://fonts.google.com/download?family=Fira%20Mono > Fira_Mono.zip
	unzip Fira_Mono.zip
	rm Fira_Mono.zip
	mkdir -p /app/share/fonts
	cp ./* /app/share/fonts
EOF
