#!/bin/sh
APPBASE="/app/greenfoot"
JAVAPATH="/app/jre"
JAVAFX_LIB="/app/javafx/lib"
CP="$APPBASE/lib/bluej.jar"
JAVAFX_CP="$JAVAFX_LIB/javafx.base.jar:$JAVAFX_LIB/javafx.controls.jar:$JAVAFX_LIB/javafx.fxml.jar:$JAVAFX_LIB/javafx.graphics.jar:$JAVAFX_LIB/javafx.media.jar:$JAVAFX_LIB/javafx.properties.jar:$JAVAFX_LIB/javafx.swing.jar:$JAVAFX_LIB/javafx.web.jar"
"$JAVAPATH/bin/java" -Djavafx.embed.singleThread=true -Dawt.useSystemAAFontSettings=on -cp "$CP:$JAVAFX_CP" bluej.Boot -greenfoot=true -bluej.compiler.showunchecked=false -javafxpath="$JAVAFX_CP" "$@"
