#!/bin/sh
export JAVA_HOME="/app/jre"
export PATH="/app/jre/bin:$PATH"
export PATH_TO_FX="/app/openjfx/lib"

export HMCL_USER_HOME="${HMCL_USER_HOME:-$XDG_DATA_HOME/hmcl}"
export HMCL_LOCAL_HOME="${HMCL_LOCAL_HOME:-$HMCL_USER_HOME/local-stable}"
export HMCL_DEPENDENCIES_DIR="${HMCL_DEPENDENCIES_DIR:-$HMCL_USER_HOME/dependencies}"

exec /app/jre/bin/java \
  -Dhmcl.offline.auth.restricted=true \
  --module-path "$PATH_TO_FX" \
  --add-modules ALL-MODULE-PATH \
  -jar /app/lib/hmcl/hmcl.jar "$@"
