#!/bin/sh
export JAVA_HOME="/app/jre"
export PATH="/app/jre/bin:$PATH"
export PATH_TO_FX="/app/openjfx/lib"

exec /app/jre/bin/java \
  -Dhmcl.offline.auth.restricted=true \
  --module-path "$PATH_TO_FX" \
  --add-modules ALL-MODULE-PATH \
  -jar /app/lib/hmcl/hmcl.jar "$@"
