#!/bin/bash
if [ ! -d "$XDG_DATA_HOME/i2pd" ]; then
    mkdir -p $XDG_DATA_HOME/.i2pd
    cp /app/i2pd/i2pd.conf $XDG_DATA_HOME/.i2pd
    cp /app/i2pd/tunnels.conf $XDG_DATA_HOME/.i2pd
    ln -s /app/i2pd/certificates $XDG_DATA_HOME/.i2pd/certificates
fi

ulimit -n 8192
i2pd_qt --datadir=$XDG_DATA_HOME/.i2pd
