#!/bin/sh
set -eu

export HOME="$XDG_DATA_HOME/home"
mkdir -p "$HOME" "$XDG_DATA_HOME/ntws"

jre_home=/app/extra/ibkr/jre
jre_library_path="$jre_home/lib:$jre_home/lib/server"
export LD_LIBRARY_PATH="$jre_library_path${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

export INSTALL4J_NO_DB=true
export INSTALL4J_JAVA_HOME_OVERRIDE="$jre_home"

extra_vm_params="-Duser.home=$HOME -DappConfigDir=$XDG_DATA_HOME/ntws -Dtwslaunch.autoupdate.serviceImpl=twslaunch.autoupdate.DummyAutoUpdateService"
if [ "${INSTALL4J_ADD_VM_PARAMS:-}" ]; then
    export INSTALL4J_ADD_VM_PARAMS="$INSTALL4J_ADD_VM_PARAMS $extra_vm_params"
else
    export INSTALL4J_ADD_VM_PARAMS="$extra_vm_params"
fi

exec /app/extra/ibkr/ntws "$@"
