#!/bin/bash

shopt -s nullglob
for dir in fcitx5*/{data,icons,icon}/{16x16,22x22,24x24,32x32,48x48,64x64,128x128,256x256,scalable}; do
    pushd .
    cd $dir
    for icon in `find . -type f`; do
        install -vDm644 $icon ${FLATPAK_DEST}/share/icons/hicolor/`basename $dir`/$icon
    done
    popd
done
