app-id: io.github.realmazharhussain.GdmSettings
command: gdm-settings
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: "42"
finish-args:
  - --share=ipc
  - --device=dri
  - --socket=wayland
  - --socket=fallback-x11
  - --talk-name=org.freedesktop.Flatpak
  - --filesystem=host-os
  - --filesystem=host-etc
cleanup:
  - /bin/blueprint-compiler
  - /lib/*/site-packages/blueprintcompiler
  - /include
  - /lib/pkgconfig
  - /man
  - /share/doc
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - '*.la'
  - '*.a'
modules:
  - name: blueprint-compiler
    builddir: true
    buildsystem: meson
    sources:
      - type: git
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
        branch: main
  - name: gdm-settings
    builddir: true
    buildsystem: meson
    config-opts:
      - --buildtype=release
    sources:
      - type: archive
        url: https://github.com/realmazharhussain/gdm-settings/archive/refs/tags/v0.5.tar.gz
        sha256: cf72a268ef12a6d91c5dec2e80aff8663f87df850c28636db2ea6f2cc687a228
