#!/bin/bash

# Copyright 2021 Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

function error-message {
    cat << EOM
ioquake3 needs the official Quake 3 .pk3-files to function
properly (specifically pak0.pk3 … pak8.pk3).

One way to obtain these files is to buy Quake 3 Arena on
Steam, and extract the files from the installation directory.

Once you've obtained the files, copy them to:

    ~/.var/app/org.ioquake3.IOQuake3/data/baseq3/

… and restart ioquake3
EOM
}

# Ensure ioquake3 reaches our pak-files and configs.
ln -ns "${XDG_DATA_HOME}" "${HOME}/.q3a"

for i in $(seq 0 8); do
    if [ ! -f "${XDG_DATA_HOME}/baseq3/pak${i}.pk3" ]; then
        zenity --error      \
               --width=400  \
               --height=200 \
               --text="$(error-message)"
        exit 2
    fi
done

/app/games/quake3/ioquake.x86_64
