#! /bin/bash

# make a mount directory for saving filters, accounts, etc from the application instead of giving full permission to the user's home directory
mkdir -p "$XDG_DATA_HOME/jEveAssets_mnt"
ln -s "$XDG_DATA_HOME/jEveAssets_mnt" "$HOME/jEveAssets_mnt"

java -jar /app/jEveAssets/jeveassets.jar "$@"
