#!/bin/sh

for i in {0..9}; do
    test -S $XDG_RUNTIME_DIR/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
done

WAYLAND=""

if [ "$XDG_SESSION_TYPE" == "wayland" ]
then
	WAYLAND="--ozone-platform=wayland"
fi

km "$@" $WAYLAND
