#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_

#define LAST_COMMIT_POSITION_NUM 9999
#define LAST_COMMIT_POSITION "9999 (ffffffffffff)"

#endif  // OUT_LAST_COMMIT_POSITION_H_
