#!/bin/sh
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

[ -d "$XDG_CONFIG_HOME/cataclysm-dda/config" ] || mkdir -p $XDG_CONFIG_HOME/cataclysm-dda/config

[ -d "$XDG_CONFIG_HOME/cataclysm-dda/save" ] || mkdir -p $XDG_CONFIG_HOME/cataclysm-dda/save

[ -d "$XDG_CONFIG_HOME/cataclysm-dda/templates" ] || mkdir -p $XDG_CONFIG_HOME/cataclysm-dda/templates

[ -d "$XDG_CONFIG_HOME/cataclysm-dda/gfx" ] || mkdir -p $XDG_CONFIG_HOME/cataclysm-dda/gfx
cp -r /app/cataclysm-dda/gfx/* $XDG_CONFIG_HOME/cataclysm-dda/gfx/

[ -d "$XDG_CONFIG_HOME/cataclysm-dda/sound" ] || mkdir -p $XDG_CONFIG_HOME/cataclysm-dda/sound
cp -r /app/cataclysm-dda/data/sound/* $XDG_CONFIG_HOME/cataclysm-dda/sound/

cd /app/cataclysm-dda && ./cataclysm-launcher --configdir $XDG_CONFIG_HOME/cataclysm-dda/config --userdir $XDG_CONFIG_HOME/cataclysm-dda
