#!/bin/sh

cd /app/cataclysm-dda && ./cataclysm-launcher \
    --configdir "$XDG_CONFIG_HOME/cataclysm-dda/" \
    --userdir "$XDG_DATA_HOME/cataclysm-dda/data/" \
    --savedir "$XDG_DATA_HOME/cataclysm-dda/save/"

