diff --git a/Makefile b/Makefile
index 815e50c9..41ce3c0b 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,10 @@
 
 #------------------------------------------------------------------------------
 
-BUILD := $(shell head -n1 .build 2> /dev/null || echo release)
+BUILD := release
 
 VERSION := 1.6.0
-VERSION := $(shell sh scripts/version.sh "$(BUILD)" "$(VERSION)" \
+#VERSION := $(shell sh scripts/version.sh "$(BUILD)" "$(VERSION)" \
 	"share/version.in.h" "share/version.h" ".version")
 
 $(info Will make a "$(BUILD)" build of Neverball $(VERSION).)
