diff -ruN gengetopt-2.22.6/src/Makefile.am gengetopt-2.22.6-new/src/Makefile.am
--- gengetopt-2.22.6/src/Makefile.am	2012-11-02 13:26:54.000000000 +0000
+++ gengetopt-2.22.6-new/src/Makefile.am	2017-10-01 21:28:19.072113358 +0100
@@ -51,7 +51,7 @@
 	@LTLIBOBJS@ \
 	skels/libgen.la
 
-LDADD = $(top_builddir)/src/libgengetopt.la
+LDADD = libgengetopt.la
 
 EXTRA_DIST = parser.h argsdef.h gengetopt.h ggos.h gm.h gnugetopt.h \
 cmdline.c cmdline.h \
