#!/bin/sh

export MENDELEY_BASE=/app/extra
export MENDELEY_BIN=/app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64
export MENDELEY_BUNDLED_CPP_LIB=/app/extra/lib/cpp
export MENDELEY_BUNDLED_QT_LIBRARY=/app/extra/lib/qt
export MENDELEY_BUNDLED_QT_PLUGIN=/app/extra/lib/mendeleydesktop/plugins
export MENDELEY_BUNDLED_SSL_LIB=/app/extra/lib/ssl
export MENDELEY_LIB=/app/extra/lib
export SCRIPT=/app/extra/bin/mendeleydesktop 
export MENDELEY_BUNDLED_QT_PLUGIN_PATH=/app/extra/lib/mendeleydesktop/plugins
export LD_LIBRARY_PATH=/usr/lib:/app/extra/lib/ssl:/app/extra/lib:/app/extra/lib/qt:/app/extra

/app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64 $@
