#!/bin/bash

source /app/bin/nest_vars.sh

# export NESTML_MODULES_PATH="${NESTML_MODULES_PATH:-/tmp/nestmlmodules}"
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NESTML_MODULES_PATH}

export NEST_SERVER_DISABLE_AUTH=1
export NEST_SERVER_DISABLE_RESTRICTION=1
export NEST_SERVER_ENABLE_EXEC_CALL=1
export NEST_SERVER_MODULES="import nest; import numpy; import numpy as np"

# Start NEST Server as daemon
export NEST_SERVER_DAEMON=1
/app/bin/nest-server start

# Start NESTML Server as daemon
# export NESTML_SERVER_DAEMON=1
# /app/bin/nestml-server start

# Start NEST Desktop
/app/bin/nest-desktop --no-sandbox

# Stop NEST Server
/app/bin/nest-server stop

# Stop NESTML Server
# /app/bin/nestml-server stop