#!/bin/bash
CVARS="+set fs_basegame baseoa +set protocol 71 +set com_protocol 72 +set cl_voip 1"

arch="$(uname -m)"
case "$arch" in
    x86_64) q3e_arch="x64" ;;
    aarch64) q3e_arch="aarch64" ;;
esac

exec quake3e.${q3e_arch} $CVARS "$@"
