#!/bin/sh

# Determine the architecture of the system
arch=$(uname -m)
case "$arch" in
    x86_64)
        omg_arch="x64"
        ;;
    aarch64)
        omg_arch="arm64"
        ;;
esac

# Execute the omega binary with the default arguments
exec /app/share/openarena/omega-$omg_arch +set fs_homepath "${XDG_DATA_HOME}" "$@"
