#!/usr/bin/env bash

terminal()
{
  lxterminal --title="terminal" "${@}"
}

export prompt='[\w]\$ ';

if [[ -n "${1}" ]]; then
  dir="$( dirname "${1}" )";
  file="$( basename "${1}" )";
  terminal --working-directory="${dir}" -e "ls -la \"${file}\"; PS1=\"${prompt}\" bash";
else
  terminal -e "PS1=\"${prompt}\" bash";
fi

