#!/bin/sh

for i in "$@"
do
  case $i in
	--module=*)
	MODULENAME="${i#*=}"
	shift
	;;
	*)
	ARGS="$ARGS $i"
	shift
	;;
  esac
done


cat <<EOF > Makefile
all:
	echo "Nothing"

install:
	CXX=/usr/bin/g++ CC=/usr/bin/gcc PYTHONUSERBASE=/app/ pip3 install --user $MODULENAME;
	cd /tmp/
	mkdir pandoc_dl && cd pandoc_dl
	curl -L https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb > pandoc.deb
	ar x pandoc.deb
	tar xf data.tar.*
	cp ./usr/bin/pandoc /app/bin/pandoc
	cp ./usr/bin/pandoc-citeproc /app/bin/pandoc-citeproc
	mkdir -p /app/share/
	cp ./usr/share/doc/pandoc/copyright /app/share/pandoc.copyright
	cd ..
	rm -rf /tmp/pandoc_dl
EOF
