#!/bin/sh

for i in "$@"
do
  case $i in
    --module=*)
    MODULENAME="${i#*=}"
    shift
    ;;
    *)
    ARGS="$ARGS $i"
    shift
    ;;
  esac
done

cat <<EOF > Makefile
all:
	echo "Nothing"

install:
	CXX=/usr/bin/g++ CC=/usr/bin/gcc PYTHONUSERBASE=/app/ pip2 install --user $MODULENAME

EOF

