#!/bin/sh
PYTHON_VERSION=$(python3 -c 'import sys; print(sys.version[:3])')

sip-install \
    --qt-shared \
    --concatenate 1 \
    --confirm-license \
    --debug \
    --verbose \
    --build-dir=${FLATPAK_BUILDER_BUILDDIR}/tmp \
    --target-dir=${FLATPAK_DEST}/lib/python${PYTHON_VERSION}/site-packages \
    --enable=QtCore \
    --enable=QtGui \
    --enable=QtNetwork \
    --enable=QtWidgets \
    --no-dbus-python \
    --no-designer-plugin \
    --no-docstrings \
    --no-qml-plugin \
    --no-tools \
    --qmake-setting QMAKE_CFLAGS="$CFLAGS" \
    --qmake-setting QMAKE_CXXFLAGS="$CXXFLAGS" \
    --qmake-setting QMAKE_LFLAGS="$LDFLAGS"
