.TH RETEXT 1

.SH NAME
ReText \- Text editor for Markdown and ReStructuredText

.SH SYNOPSIS
.B retext
\fIFILE\fR

.SH DESCRIPTION
.PP
ReText is a simple editor for Markdown and ReStructuredText markup languages.
.PP
Supported output formats: Plain text, HTML, ODT, PDF. Also,
ReText can upload documents to Google Docs.
.PP
It is written in Python using Qt libraries.

.SH AUTHOR
This manual page was written by Dmitry Shachnev <mitya57@gmail.com>.
