#!/usr/bin/env bash

# Enable Wayland support for Avalonia if running under Wayland
if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
    export AVALONIA_WAYLAND=1
fi

mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/applications"
exec /app/bin/root-app/usr/bin/Root "$@"