#!/usr/bin/env bash

# Enable Wayland support for Avalonia if running under Wayland
if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
    export AVALONIA_WAYLAND=1
fi

APPS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
mkdir -p "$APPS_DIR"
if [ ! -e /app/bin/root-app/usr/bin/.local/share/applications ]; then
    ln -sf "$APPS_DIR" /app/bin/root-app/usr/bin/.local/share/applications 2>/dev/null || true
fi

exec /app/bin/root-app/usr/bin/Root "$@"