#!/bin/sh

if [ $LANG == "ru_RU.UTF-8" ]; then
    /app/dosbox-staging/dosbox -conf /app/mechwarrior-rus/dosbox-staging-rus.conf
else
    /app/dosbox-staging/dosbox -conf /app/mechwarrior/dosbox-staging.conf
fi