#!/bin/sh
# (script copied from https://aur.archlinux.org/packages/intiface-central-bin)
# Because of issue #40 on GitHub, intiface_central needs to be executed
# in the folder containing the 'lib' subdirectory as library loading
# from LD_LIBRARY_PATH is not supported.

cd /app/lib/intiface_central/
./intiface_central
