#!/bin/env sh
# Wrapper script for flatpak

runscript() {
    echo "$@" | flatpak-spawn --env=TERM=xterm-256color --host script --quiet /dev/null 
}

runcommand() {
    flatpak-spawn --env=TERM=xterm-256color --host $@
}

hostcopy() {
    CAT='cat > '
    COMMAND=$CAT$2
    echo $COMMAND
    cat "$1" | flatpak-spawn --env=TERM=xterm-256color --host bash -c "$COMMAND"
}

TMP=`runcommand mktemp -d`
hostcopy /app/bin/setup_rules.sh $TMP/setup_rules.sh
runcommand chmod +x $TMP/setup_rules.sh
runcommand pkexec $TMP/setup_rules.sh
runcommand rm $TMP/setup_rules.sh
runcommand rmdir $TMP