#!/bin/sh
/app/jre/bin/java -cp /app/squirrelsql/squirrel-sql.jar:/app/squirrelsql/lib/*:/app/jdbc-drivers/* -splash:"/app/squirrelsql/icons/splash.jpg" net.sourceforge.squirrel_sql.client.Main --user-settings-dir $XDG_CONFIG_HOME
