#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-net.gpro.gproapp}"

declare -a FLAGS=(--ozone-platform-hint=auto)

if [[ $XDG_SESSION_TYPE == "wayland" ]] && [[ -c /dev/nvidia0 ]]
then
    echo "Using NVIDIA on Wayland, disabling gpu sandbox"
    FLAGS+=(--disable-gpu-sandbox)
fi

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/GPRO/gpro flatpak=1 --no-sandbox "${FLAGS[@]}" "$@"
