#!/usr/bin/env bash

TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-dev.vencord.Vesktop}"
declare -a FLAGS=(--ozone-platform-hint=auto)

if [[ $XDG_SESSION_TYPE == "wayland" ]]
then
    WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}

    if [[ -c /dev/nvidia0 ]]
    then
      echo "Using NVIDIA on Wayland, disabling gpu sandbox"
      FLAGS+=(--disable-gpu-sandbox)
    fi
fi

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/vesktop/vencorddesktop.bin "${FLAGS[@]}" "$@"