#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-net.gpro.gproapp}"

declare -a FLAGS=(--ozone-platform-hint=auto)

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
exec zypak-wrapper /app/GPRO/gpro flatpak=1 --no-sandbox "${FLAGS[@]}" "$@"