#!/usr/bin/sh
for i in {0..9}; do
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf "$XDG_RUNTIME_DIR"/app/com.discordapp.Discord/discord-ipc-$i "$XDG_RUNTIME_DIR"/discord-ipc-$i;
done

export OSU_EXTERNAL_UPDATE_PROVIDER=1

exec '/app/bin/osu!' "$@"
