#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-net.gpro.gproapp}"

declare -a FLAGS=(--ozone-platform-hint=auto)

#when wayland is supported in future update
#if [[ $XDG_SESSION_TYPE == "wayland" ]] && [[ -c /dev/nvidia0 ]]
#then
#    echo "Using NVIDIA on Wayland, disabling gpu sandbox"
#    FLAGS+=(--disable-gpu-sandbox)
#    FLAGS+=(--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer)
#    FLAGS+=(--ozone-hint=auto)
#fi

echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
exec zypak-wrapper /app/GPRO/gpro flatpak=1 "${FLAGS[@]}" "$@"