#!/usr/bin/env bash

export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-app.legcord.Legcord}"

declare -a FLAGS=(--enable-speech-dispatcher)

if [[ $XDG_SESSION_TYPE == "wayland" && -z "$DISPLAY" ]]; then
    if [[ -c /dev/nvidia0 ]]; then
        echo "Using NVIDIA on Wayland, disabling gpu sandbox"
        FLAGS+=(--disable-gpu-sandbox)
    fi

    WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}
    if [[ "${WAYLAND_SOCKET:0:1}" != "/" ]]; then
        WAYLAND_SOCKET="$XDG_RUNTIME_DIR/$WAYLAND_SOCKET"
    fi

    echo "Running on native Wayland"
else
    if [[ $XDG_SESSION_TYPE == "x11" ]]; then
        echo "Running on native X11"
        echo "To use Wayland instead, use a Wayland session."
    else
        echo "Running on X11 via Xwayland"
        echo "The Wayland socket permission needs to be added to run on Wayland."
    fi

fi

echo "Passing the following arguments to Electron:" "${FLAGS[@]}" "$@"
zypak-wrapper /app/bin/legcord/Legcord.bin "${FLAGS[@]}" "$@"
