#!/bin/bash
#Run game or given command in environment

cd "${HOME}/.local/share/Steam/steamapps/common/Supreme Commander Forged Alliance"
DEF_CMD=("${HOME}/.local/share/Steam/steamapps/common/Supreme Commander Forged Alliance/bin/SupremeCommander.exe")
PATH="${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/bin/:/usr/bin:/bin" \
	TERM="xterm" \
	WINEDEBUG="-all" \
	WINEDLLPATH="${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/lib64//wine:${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/lib//wine" \
	LD_LIBRARY_PATH="${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/lib64/:${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/lib/:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases" \
	WINEPREFIX="${HOME}/.local/share/Steam/steamapps/compatdata/9420/pfx/" \
	WINEFSYNC="1" \
	SteamGameId="9420" \
	SteamAppId="9420" \
	WINEDLLOVERRIDES="steam.exe=b;dotnetfx35.exe=b;mfplay=n;dxvk_config=n;d3d11=n;d3d10=n;d3d10core=n;d3d10_1=n;d3d9=n" \
	STEAM_COMPAT_CLIENT_INSTALL_PATH="${HOME}/.local/share/Steam" \
	WINE_LARGE_ADDRESS_AWARE="1" \
	GST_PLUGIN_SYSTEM_PATH_1_0="${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/lib64/gstreamer-1.0:${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/lib/gstreamer-1.0" \
	WINE_GST_REGISTRY_DIR="${HOME}/.local/share/Steam/steamapps/compatdata/9420/gstreamer-1.0/" \
	MEDIACONV_AUDIO_DUMP_FILE="${HOME}/.local/share/Steam/steamapps/shadercache/9420/fozmediav1/audio.foz" \
	MEDIACONV_AUDIO_TRANSCODED_FILE="${HOME}/.local/share/Steam/steamapps/shadercache/9420/swarm/transcoded_audio.foz" \
	MEDIACONV_VIDEO_DUMP_FILE="${HOME}/.local/share/Steam/steamapps/shadercache/9420/fozmediav1/video.foz" \
	MEDIACONV_VIDEO_TRANSCODED_FILE="${HOME}/.local/share/Steam/steamapps/shadercache/9420/swarm/transcoded_video.foz" \
	"${HOME}/.local/share/Steam/steamapps/common/Proton 5.13/dist/bin/wine" steam.exe "${@:-${DEF_CMD[@]}}"
