#!/bin/sh

DIR=${XDG_DATA_HOME}/thinkorswim

if [ ! -f "${DIR}/thinkorswim" ]; then
    sh /app/extra/thinkorswim_installer.sh -q -dir "${DIR}"
fi

# NOTE(jkoelker) I don't know why, but removing `ACCOUNT_MODELS` fixes the
#                wayland window rehoming issue (main window doesn't show).
for workspace in "${DIR}"/workspace.*.tos.prod.xml; do
    sed -i 's/WORKSPACE ACCOUNT_MODELS=[^ ]*/WORKSPACE/' "${workspace}"
done

exec "${DIR}/thinkorswim" "$@"
