#!/bin/bash

# Copyright 2023 Daniel Rusek <mail@asciiwolf.com>
# Based on ioquake3 launcher script by Mattias Bengtsson
# SPDX-License-Identifier: GPL-3.0-or-later

function error-message {
    cat << EOM
Unreal Tournament needs the official game files
to function properly.

Please copy the game installation directory content
from Steam, GOG or retail CD release here:

    ~/.var/app/com.epicgames.ut99/data/

… and restart Unreal Tournament
EOM
}

for i in Maps Sounds System Textures; do
    if [ ! -d "${XDG_DATA_HOME}/${i}" ]; then
        zenity --error      \
               --width=400  \
               --height=200 \
               --text="$(error-message)"
        exit 2
    fi
done

if [ ! -f "${XDG_DATA_HOME}/patched" ]; then
    cp -rf /app/extra/* "${XDG_DATA_HOME}"/
    touch "${XDG_DATA_HOME}"/patched
fi

cd ${XDG_DATA_HOME}/System*64
exec ./ut-bin-* "$@"
