#!/bin/sh
set -eu

export TMPDIR="${XDG_RUNTIME_DIR:-/tmp}/app/${FLATPAK_ID:-com.victumapp.pos}"
mkdir -p "$TMPDIR"

exec /app/VictumPOS/victumpos \
  --no-sandbox \
  --disable-setuid-sandbox \
  --disable-seccomp-filter-sandbox \
  --disable-gpu-sandbox \
  --no-zygote \
  "$@"
