name: mobile-config-firefox
buildsystem: simple
sources:
  - type: git
    url: https://gitlab.postmarketos.org/postmarketOS/mobile-config-firefox
    commit: aae92d26e6cac47f63f7b3dbc2d6b7ae0ce9d5ee
  - type: patch
    paths:
      - autoconfig.patch # loading gnome theme
      - browsercss.patch # remove close app button
build-commands:
  # flatpak uses /app/etc instead of /etc
  - sed -i 's#/etc/mobile-config-firefox#/app/etc/mobile-config-firefox#g' src/mobile-config-autoconfig.js
  # get all firefox search engines back
  # disable annoying check for default browser
  - jq 'del(.policies.SearchEngines)|.policies.DontCheckDefaultBrowser=true' src/policies.json | tee src/policies.tmp
  - mv src/policies.tmp src/policies.json
  - make install DESTDIR=/app FIREFOX_DIR=lib/firefox FIREFOX_CONFIG_DIR=lib/firefox/distribution
  - mkdir /app/etc/firefox
  # these files should be moved, otherwise they not work
  - mv /app/lib/firefox/mobile-config-autoconfig.js /app/etc/firefox/mobile-config-autoconfig.js
  - mv /app/lib/firefox/distribution/policies/policies.json /app/lib/firefox/distribution/policies.json

