//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Galaxy.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GALAXY_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       132
#define IDI_ICON2                       133
#define IDI_ICON3                       134
#define IDI_ICON4                       135
#define IDB_BITMAP2                     136
#define IDB_BITMAP1                     139
#define IDB_BITMAP3                     140
#define IDB_BITMAP4                     141
#define IDB_BITMAP5                     142
#define IDB_BITMAP6                     143
#define IDB_BITMAP7                     144
#define IDB_BITMAP8                     145
#define IDB_BITMAP9                     146
#define IDB_BITMAP10                    147
#define IDR_MENU1                       149
#define IDD_SETPROFILE                  150
#define IDB_BITMAP11                    151
#define IDB_BITMAP12                    152
#define IDB_BITMAP13                    153
#define IDB_BITMAP14                    154
#define IDB_BITMAP15                    155
#define IDB_BITMAP16                    156
#define IDB_BITMAP17                    157
#define IDB_BITMAP18                    158
#define IDB_BITMAP19                    159
#define IDI_ICON5                       160
#define IDI_ICON6                       161
#define IDB_BITMAP20                    162
#define IDB_BITMAP21                    163
#define IDB_BITMAP22                    164
#define IDB_BITMAP23                    165
#define IDB_BITMAP24                    166
#define IDB_BITMAP25                    167
#define IDD_BUDDYNAME                   168
#define IDB_BITMAP26                    169
#define IDB_BITMAP27                    170
#define IDB_BITMAP28                    171
#define IDD_STARTUP                     172
#define IDD_UPDATER                     174
#define IDB_COLUMNHEADER_END            176
#define IDB_COLUMNHEADER_SPAN           177
#define IDB_COLUMNHEADER_START          178
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 179
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 180
#define IDB_HORIZONTAL_SCROLLBAR_SPAN   181
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 183
#define IDB_VERTICLE_SCROLLBAR_SPAN     184
#define IDB_VERTICLE_SCROLLBAR_UPARROW  185
#define IDB_VERTICLE_SCROLLBAR_TOP      187
#define IDB_VERTICLE_SCROLLBAR_THUMB    188
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  189
#define IDB_VERTICLE_SCROLLBAR_BOTTOM   190
#define IDB_BITMAP29                    222
#define IDI_ICON7                       236
#define IDI_ICON8                       239
#define IDD_HELPBOX                     240
#define IDC_LIST1                       1000
#define IDC_BUTTON1                     1006
#define IDC_LIST3                       1007
#define IDC_LIST4                       1008
#define IDC_LIST5                       1009
#define IDC_BUDDYLIST                   1009
#define IDC_PROGRESS1                   1010
#define IDC_BUTTON2                     1011
#define IDC_EDIT3                       1012
#define IDC_BUTTON3                     1013
#define IDC_EDIT1                       1014
#define IDC_PLAYEREMAIL                 1015
#define IDC_STATUS2                     1015
#define IDC_LIST2                       1016
#define IDC_GAMEPATH                    1016
#define IDC_BUTTON4                     1017
#define IDC_BUTTON5                     1018
#define IDC_PLAYERNAME                  1018
#define IDC_BUTTON6                     1019
#define IDC_JOINATSTARTUP               1020
#define IDC_EDIT2                       1020
#define IDC_ADDBUDDY                    1021
#define IDC_BUDDYNAME                   1021
#define IDC_DELBUDDY                    1022
#define IDC_PLAYERSORT                  1023
#define IDC_PINGSORT                    1024
#define IDC_SHOWUSERS                   1025
#define IDC_IRCSERVER                   1026
#define IDC_NEWS                        1027
#define IDC_UPDATEPROGRESS              1028
#define IDC_PRIVACY                     1032
#define IDC_LINK1                       1033
#define IDC_LINK2                       1034
#define IDC_LINK3                       1035
#define IDC_LINK4                       1036
#define IDC_LINK5                       1037
#define IDC_LINK6                       1038
#define IDC_LINK7                       1039
#define ID_MENU_CONFIGURE               32771
#define ID_SERVERTOOLS_REFRESH          32772
#define ID_SERVERTOOLS_JOIN             32773
#define ID_SERVERTOOLS_LAUNCHALIENARENA 32774
#define ID_CHAT_JOINCHATCHANNEL         32777
#define ID_CHAT_LEAVECHATCHANNEL        32778
#define ID_STATS_LOOKUPSTATS            32779
#define ID_MENU_ABOUT                   32784
#define ID_MENU_HELP                    32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
