name: Update commit hash
on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00

jobs:
  change-commit:
    name: Change the commit hash to the latest upstream one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change commit
        run: |
          commit_and_tag=$(git ls-remote --sort=version:refname https://github.com/PCSX2/pcsx2 'refs/tags/v*' | awk 'END { print $0 }' | tr -d '^{}')
          commit=${commit_and_tag%%	*}
          tag=${commit_and_tag##*/}
          sed -i "/pcsx2.git/{n;s/tag.*/tag\": \"$tag\",/;n;s/commit.*/commit\": \"$commit\"/}" net.pcsx2.PCSX2.json
          sed -i "s|    <release .*|    <release date=\"$(date -I)\" version=\"$tag\"/>|" net.pcsx2.PCSX2.metainfo.xml
      - name: Push the change
        run: |
          git config user.name CI
          git config user.email ""
          git add net.pcsx2.PCSX2.json net.pcsx2.PCSX2.metainfo.xml
          git commit -m "Update pcsx2.git" || exit 0
          git push
