#!/usr/bin/python3

import argparse
import os

import github

if __name__ == "__main__":
    usage = (
        "lists repositories belonging to github organization\n"
        "example: gh-ls-org foobar | xargs -P4 -L1 git clone --recursive"
    )
    parser = argparse.ArgumentParser(usage=usage)
    parser.add_argument("organization", help="name of github organization")
    args = parser.parse_args()

    github_token = os.environ["GITHUB_TOKEN"]
    g = github.Github(github_token, per_page=200)

    org = g.get_organization(args.organization)

    for repo in org.get_repos():
        if not repo.archived:
            print(repo.html_url)
