#!/bin/sh

set -e

qbs setup-toolchains --settings-dir .qbs-settings --type gcc /usr/bin/g++ gcc
qbs setup-qt --settings-dir .qbs-settings /usr/bin/qmake qt5
qbs config --settings-dir .qbs-settings profiles.qt5.baseProfile gcc
qbs config --settings-dir .qbs-settings --list
