/* SearchEntry.c generated by valac 0.40.11, the Vala compiler
 * generated from SearchEntry.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define WIDGETS_TYPE_SEARCH_ENTRY (widgets_search_entry_get_type ())
#define WIDGETS_SEARCH_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIDGETS_TYPE_SEARCH_ENTRY, WidgetsSearchEntry))
#define WIDGETS_SEARCH_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIDGETS_TYPE_SEARCH_ENTRY, WidgetsSearchEntryClass))
#define WIDGETS_IS_SEARCH_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIDGETS_TYPE_SEARCH_ENTRY))
#define WIDGETS_IS_SEARCH_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIDGETS_TYPE_SEARCH_ENTRY))
#define WIDGETS_SEARCH_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIDGETS_TYPE_SEARCH_ENTRY, WidgetsSearchEntryClass))

typedef struct _WidgetsSearchEntry WidgetsSearchEntry;
typedef struct _WidgetsSearchEntryClass WidgetsSearchEntryClass;
typedef struct _WidgetsSearchEntryPrivate WidgetsSearchEntryPrivate;
enum  {
	WIDGETS_SEARCH_ENTRY_0_PROPERTY,
	WIDGETS_SEARCH_ENTRY_NUM_PROPERTIES
};
static GParamSpec* widgets_search_entry_properties[WIDGETS_SEARCH_ENTRY_NUM_PROPERTIES];

#define TYPE_BYTE (byte_get_type ())
#define BYTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BYTE, Byte))
#define BYTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BYTE, ByteClass))
#define IS_BYTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BYTE))
#define IS_BYTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BYTE))
#define BYTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BYTE, ByteClass))

typedef struct _Byte Byte;
typedef struct _ByteClass ByteClass;

struct _WidgetsSearchEntry {
	GtkSearchEntry parent_instance;
	WidgetsSearchEntryPrivate * priv;
};

struct _WidgetsSearchEntryClass {
	GtkSearchEntryClass parent_class;
};


static gpointer widgets_search_entry_parent_class = NULL;

GType widgets_search_entry_get_type (void) G_GNUC_CONST;
WidgetsSearchEntry* widgets_search_entry_new (void);
WidgetsSearchEntry* widgets_search_entry_construct (GType object_type);
static GObject * widgets_search_entry_constructor (GType type,
                                            guint n_construct_properties,
                                            GObjectConstructParam * construct_properties);
static gboolean _widgets_search_entry___lambda112_ (WidgetsSearchEntry* self);
GType byte_get_type (void) G_GNUC_CONST;
Byte* byte_get_instance (void);
void byte_toggle_playing_action_enabled (Byte* self,
                                         gboolean b);
static gboolean __widgets_search_entry___lambda112__gtk_widget_focus_in_event (GtkWidget* _sender,
                                                                        GdkEventFocus* event,
                                                                        gpointer self);
static gboolean _widgets_search_entry___lambda113_ (WidgetsSearchEntry* self);
static gboolean __widgets_search_entry___lambda113__gtk_widget_focus_out_event (GtkWidget* _sender,
                                                                         GdkEventFocus* event,
                                                                         gpointer self);
static void _widgets_search_entry___lambda114_ (WidgetsSearchEntry* self);
static void __widgets_search_entry___lambda114__gtk_search_entry_search_changed (GtkSearchEntry* _sender,
                                                                          gpointer self);


WidgetsSearchEntry*
widgets_search_entry_construct (GType object_type)
{
	WidgetsSearchEntry * self = NULL;
	self = (WidgetsSearchEntry*) g_object_new (object_type, NULL);
	return self;
}


WidgetsSearchEntry*
widgets_search_entry_new (void)
{
	return widgets_search_entry_construct (WIDGETS_TYPE_SEARCH_ENTRY);
}


static gboolean
_widgets_search_entry___lambda112_ (WidgetsSearchEntry* self)
{
	gboolean result = FALSE;
	Byte* _tmp0_;
	Byte* _tmp1_;
	_tmp0_ = byte_get_instance ();
	_tmp1_ = _tmp0_;
	byte_toggle_playing_action_enabled (_tmp1_, FALSE);
	result = FALSE;
	return result;
}


static gboolean
__widgets_search_entry___lambda112__gtk_widget_focus_in_event (GtkWidget* _sender,
                                                               GdkEventFocus* event,
                                                               gpointer self)
{
	gboolean result;
	result = _widgets_search_entry___lambda112_ ((WidgetsSearchEntry*) self);
	return result;
}


static gboolean
_widgets_search_entry___lambda113_ (WidgetsSearchEntry* self)
{
	gboolean result = FALSE;
	Byte* _tmp0_;
	Byte* _tmp1_;
	_tmp0_ = byte_get_instance ();
	_tmp1_ = _tmp0_;
	byte_toggle_playing_action_enabled (_tmp1_, TRUE);
	result = FALSE;
	return result;
}


static gboolean
__widgets_search_entry___lambda113__gtk_widget_focus_out_event (GtkWidget* _sender,
                                                                GdkEventFocus* event,
                                                                gpointer self)
{
	gboolean result;
	result = _widgets_search_entry___lambda113_ ((WidgetsSearchEntry*) self);
	return result;
}


static void
_widgets_search_entry___lambda114_ (WidgetsSearchEntry* self)
{
	Byte* _tmp0_;
	Byte* _tmp1_;
	_tmp0_ = byte_get_instance ();
	_tmp1_ = _tmp0_;
	byte_toggle_playing_action_enabled (_tmp1_, FALSE);
}


static void
__widgets_search_entry___lambda114__gtk_search_entry_search_changed (GtkSearchEntry* _sender,
                                                                     gpointer self)
{
	_widgets_search_entry___lambda114_ ((WidgetsSearchEntry*) self);
}


static GObject *
widgets_search_entry_constructor (GType type,
                                  guint n_construct_properties,
                                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	WidgetsSearchEntry * self;
	GtkStyleContext* _tmp0_;
	parent_class = G_OBJECT_CLASS (widgets_search_entry_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WIDGETS_TYPE_SEARCH_ENTRY, WidgetsSearchEntry);
	g_object_set ((GtkWidget*) self, "margin", 6, NULL);
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_CENTER);
	gtk_widget_set_hexpand ((GtkWidget*) self, TRUE);
	_tmp0_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_class (_tmp0_, "search-entry");
	g_signal_connect_object ((GtkWidget*) self, "focus-in-event", (GCallback) __widgets_search_entry___lambda112__gtk_widget_focus_in_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "focus-out-event", (GCallback) __widgets_search_entry___lambda113__gtk_widget_focus_out_event, self, 0);
	g_signal_connect_object ((GtkSearchEntry*) self, "search-changed", (GCallback) __widgets_search_entry___lambda114__gtk_search_entry_search_changed, self, 0);
	return obj;
}


static void
widgets_search_entry_class_init (WidgetsSearchEntryClass * klass)
{
	widgets_search_entry_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = widgets_search_entry_constructor;
}


static void
widgets_search_entry_instance_init (WidgetsSearchEntry * self)
{
}


GType
widgets_search_entry_get_type (void)
{
	static volatile gsize widgets_search_entry_type_id__volatile = 0;
	if (g_once_init_enter (&widgets_search_entry_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WidgetsSearchEntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) widgets_search_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WidgetsSearchEntry), 0, (GInstanceInitFunc) widgets_search_entry_instance_init, NULL };
		GType widgets_search_entry_type_id;
		widgets_search_entry_type_id = g_type_register_static (gtk_search_entry_get_type (), "WidgetsSearchEntry", &g_define_type_info, 0);
		g_once_init_leave (&widgets_search_entry_type_id__volatile, widgets_search_entry_type_id);
	}
	return widgets_search_entry_type_id__volatile;
}



