/* TrackRow.c generated by valac 0.40.11, the Vala compiler
 * generated from TrackRow.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <granite.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define WIDGETS_TYPE_TRACK_ROW (widgets_track_row_get_type ())
#define WIDGETS_TRACK_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRow))
#define WIDGETS_TRACK_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRowClass))
#define WIDGETS_IS_TRACK_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIDGETS_TYPE_TRACK_ROW))
#define WIDGETS_IS_TRACK_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIDGETS_TYPE_TRACK_ROW))
#define WIDGETS_TRACK_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRowClass))

typedef struct _WidgetsTrackRow WidgetsTrackRow;
typedef struct _WidgetsTrackRowClass WidgetsTrackRowClass;
typedef struct _WidgetsTrackRowPrivate WidgetsTrackRowPrivate;

#define OBJECTS_TYPE_TRACK (objects_track_get_type ())
#define OBJECTS_TRACK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OBJECTS_TYPE_TRACK, ObjectsTrack))
#define OBJECTS_TRACK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OBJECTS_TYPE_TRACK, ObjectsTrackClass))
#define OBJECTS_IS_TRACK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OBJECTS_TYPE_TRACK))
#define OBJECTS_IS_TRACK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OBJECTS_TYPE_TRACK))
#define OBJECTS_TRACK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OBJECTS_TYPE_TRACK, ObjectsTrackClass))

typedef struct _ObjectsTrack ObjectsTrack;
typedef struct _ObjectsTrackClass ObjectsTrackClass;

#define WIDGETS_TYPE_COVER (widgets_cover_get_type ())
#define WIDGETS_COVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIDGETS_TYPE_COVER, WidgetsCover))
#define WIDGETS_COVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIDGETS_TYPE_COVER, WidgetsCoverClass))
#define WIDGETS_IS_COVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIDGETS_TYPE_COVER))
#define WIDGETS_IS_COVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIDGETS_TYPE_COVER))
#define WIDGETS_COVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIDGETS_TYPE_COVER, WidgetsCoverClass))

typedef struct _WidgetsCover WidgetsCover;
typedef struct _WidgetsCoverClass WidgetsCoverClass;
enum  {
	WIDGETS_TRACK_ROW_0_PROPERTY,
	WIDGETS_TRACK_ROW_TRACK_PROPERTY,
	WIDGETS_TRACK_ROW_NUM_PROPERTIES
};
static GParamSpec* widgets_track_row_properties[WIDGETS_TRACK_ROW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define SERVICES_TYPE_SCAN (services_scan_get_type ())
#define SERVICES_SCAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SERVICES_TYPE_SCAN, ServicesScan))
#define SERVICES_SCAN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SERVICES_TYPE_SCAN, ServicesScanClass))
#define SERVICES_IS_SCAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SERVICES_TYPE_SCAN))
#define SERVICES_IS_SCAN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SERVICES_TYPE_SCAN))
#define SERVICES_SCAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SERVICES_TYPE_SCAN, ServicesScanClass))

typedef struct _ServicesScan ServicesScan;
typedef struct _ServicesScanClass ServicesScanClass;
typedef struct _ServicesScanPrivate ServicesScanPrivate;

#define OBJECTS_TYPE_PLAYLIST (objects_playlist_get_type ())
#define OBJECTS_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OBJECTS_TYPE_PLAYLIST, ObjectsPlaylist))
#define OBJECTS_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OBJECTS_TYPE_PLAYLIST, ObjectsPlaylistClass))
#define OBJECTS_IS_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OBJECTS_TYPE_PLAYLIST))
#define OBJECTS_IS_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OBJECTS_TYPE_PLAYLIST))
#define OBJECTS_PLAYLIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OBJECTS_TYPE_PLAYLIST, ObjectsPlaylistClass))

typedef struct _ObjectsPlaylist ObjectsPlaylist;
typedef struct _ObjectsPlaylistClass ObjectsPlaylistClass;

#define SERVICES_TYPE_DATABASE (services_database_get_type ())
#define SERVICES_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SERVICES_TYPE_DATABASE, ServicesDatabase))
#define SERVICES_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SERVICES_TYPE_DATABASE, ServicesDatabaseClass))
#define SERVICES_IS_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SERVICES_TYPE_DATABASE))
#define SERVICES_IS_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SERVICES_TYPE_DATABASE))
#define SERVICES_DATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SERVICES_TYPE_DATABASE, ServicesDatabaseClass))

typedef struct _ServicesDatabase ServicesDatabase;
typedef struct _ServicesDatabaseClass ServicesDatabaseClass;
typedef struct _ObjectsTrackPrivate ObjectsTrackPrivate;
typedef struct _Block12Data Block12Data;
typedef struct _ObjectsPlaylistPrivate ObjectsPlaylistPrivate;
typedef struct _Block13Data Block13Data;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_UTILS (utils_get_type ())
#define UTILS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UTILS, Utils))
#define UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_UTILS, UtilsClass))
#define IS_UTILS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UTILS))
#define IS_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_UTILS))
#define UTILS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_UTILS, UtilsClass))

typedef struct _Utils Utils;
typedef struct _UtilsClass UtilsClass;
typedef struct _UtilsPrivate UtilsPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define WIDGETS_TYPE_MENU_ITEM (widgets_menu_item_get_type ())
#define WIDGETS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WIDGETS_TYPE_MENU_ITEM, WidgetsMenuItem))
#define WIDGETS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WIDGETS_TYPE_MENU_ITEM, WidgetsMenuItemClass))
#define WIDGETS_IS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WIDGETS_TYPE_MENU_ITEM))
#define WIDGETS_IS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WIDGETS_TYPE_MENU_ITEM))
#define WIDGETS_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WIDGETS_TYPE_MENU_ITEM, WidgetsMenuItemClass))

typedef struct _WidgetsMenuItem WidgetsMenuItem;
typedef struct _WidgetsMenuItemClass WidgetsMenuItemClass;

#define DIALOGS_TYPE_TRACK_EDITOR (dialogs_track_editor_get_type ())
#define DIALOGS_TRACK_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DIALOGS_TYPE_TRACK_EDITOR, DialogsTrackEditor))
#define DIALOGS_TRACK_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DIALOGS_TYPE_TRACK_EDITOR, DialogsTrackEditorClass))
#define DIALOGS_IS_TRACK_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DIALOGS_TYPE_TRACK_EDITOR))
#define DIALOGS_IS_TRACK_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DIALOGS_TYPE_TRACK_EDITOR))
#define DIALOGS_TRACK_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DIALOGS_TYPE_TRACK_EDITOR, DialogsTrackEditorClass))

typedef struct _DialogsTrackEditor DialogsTrackEditor;
typedef struct _DialogsTrackEditorClass DialogsTrackEditorClass;
typedef struct _Block14Data Block14Data;

#define SERVICES_TYPE_PLAYER (services_player_get_type ())
#define SERVICES_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SERVICES_TYPE_PLAYER, ServicesPlayer))
#define SERVICES_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SERVICES_TYPE_PLAYER, ServicesPlayerClass))
#define SERVICES_IS_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SERVICES_TYPE_PLAYER))
#define SERVICES_IS_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SERVICES_TYPE_PLAYER))
#define SERVICES_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SERVICES_TYPE_PLAYER, ServicesPlayerClass))

typedef struct _ServicesPlayer ServicesPlayer;
typedef struct _ServicesPlayerClass ServicesPlayerClass;
typedef struct _Block15Data Block15Data;

struct _WidgetsTrackRow {
	GtkListBoxRow parent_instance;
	WidgetsTrackRowPrivate * priv;
};

struct _WidgetsTrackRowClass {
	GtkListBoxRowClass parent_class;
};

struct _WidgetsTrackRowPrivate {
	ObjectsTrack* _track;
	GtkLabel* primary_label;
	GtkLabel* secondary_label;
	GtkLabel* duration_label;
	GtkButton* favorite_button;
	GtkMenu* playlists;
	GtkMenu* menu;
	WidgetsCover* image_cover;
};

struct _ServicesScan {
	GObject parent_instance;
	ServicesScanPrivate * priv;
	gint counter;
	gint counter_max;
	gboolean is_sync;
};

struct _ServicesScanClass {
	GObjectClass parent_class;
};

struct _ObjectsTrack {
	GObject parent_instance;
	ObjectsTrackPrivate * priv;
	gint track_order;
	gint id;
	gint album_id;
	gint track;
	gint disc;
	gint play_count;
	gint is_favorite;
	gint bitrate;
	gint bpm;
	gint rating;
	gint samplerate;
	gint channels;
	gint year;
	gint playlist;
	guint64 duration;
	gchar* path;
	gchar* title;
	gchar* favorite_added;
	gchar* last_played;
	gchar* album_title;
	gchar* artist_name;
	gchar* composer;
	gchar* grouping;
	gchar* comment;
	gchar* lyrics;
	gchar* genre;
	gchar* album_artist;
	gchar* date_added;
};

struct _ObjectsTrackClass {
	GObjectClass parent_class;
};

struct _Block12Data {
	int _ref_count_;
	WidgetsTrackRow* self;
	ObjectsPlaylist* playlist;
};

struct _ObjectsPlaylist {
	GObject parent_instance;
	ObjectsPlaylistPrivate * priv;
	gint id;
	gchar* title;
	gchar* note;
	gchar* date_added;
	gchar* date_updated;
	gint num_tracks;
};

struct _ObjectsPlaylistClass {
	GObjectClass parent_class;
};

struct _Block13Data {
	int _ref_count_;
	WidgetsTrackRow* self;
	ObjectsTrack* track;
};

struct _Utils {
	GObject parent_instance;
	UtilsPrivate * priv;
	gchar* MAIN_FOLDER;
	gchar* COVER_FOLDER;
};

struct _UtilsClass {
	GObjectClass parent_class;
};

struct _Block14Data {
	int _ref_count_;
	WidgetsTrackRow* self;
	GtkRevealer* playing_revealer;
	GtkStack* options_stack;
	GtkImage* icon_favorite;
	GtkImage* icon_no_favorite;
	GtkGrid* main_grid;
};

struct _Block15Data {
	int _ref_count_;
	WidgetsTrackRow* self;
	gint track_id;
};


static gpointer widgets_track_row_parent_class = NULL;
extern ServicesScan* byte_scan_service;
extern ServicesDatabase* byte_database;
extern Utils* byte_utils;
extern ServicesPlayer* byte_player;

GType widgets_track_row_get_type (void) G_GNUC_CONST;
GType objects_track_get_type (void) G_GNUC_CONST;
GType widgets_cover_get_type (void) G_GNUC_CONST;
#define WIDGETS_TRACK_ROW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRowPrivate))
WidgetsTrackRow* widgets_track_row_new (ObjectsTrack* track);
WidgetsTrackRow* widgets_track_row_construct (GType object_type,
                                              ObjectsTrack* track);
static void widgets_track_row_activate_menu (WidgetsTrackRow* self);
static void widgets_track_row_build_context_menu (WidgetsTrackRow* self,
                                           ObjectsTrack* track);
ObjectsTrack* widgets_track_row_get_track (WidgetsTrackRow* self);
GType services_scan_get_type (void) G_GNUC_CONST;
GType objects_playlist_get_type (void) G_GNUC_CONST;
GType services_database_get_type (void) G_GNUC_CONST;
GeeArrayList* services_database_get_all_playlists (ServicesDatabase* self);
static void ___lambda86_ (WidgetsTrackRow* self);
ObjectsPlaylist* services_database_create_new_playlist (ServicesDatabase* self);
void services_database_insert_track_into_playlist (ServicesDatabase* self,
                                                   ObjectsPlaylist* playlist,
                                                   gint track_id);
static void ____lambda86__gtk_menu_item_activate (GtkMenuItem* _sender,
                                           gpointer self);
static Block12Data* block12_data_ref (Block12Data* _data12_);
static void block12_data_unref (void * _userdata_);
static void _____lambda87_ (Block12Data* _data12_);
static void ______lambda87__gtk_menu_item_activate (GtkMenuItem* _sender,
                                             gpointer self);
static Block13Data* block13_data_ref (Block13Data* _data13_);
static void block13_data_unref (void * _userdata_);
GType utils_get_type (void) G_GNUC_CONST;
GType widgets_menu_item_get_type (void) G_GNUC_CONST;
WidgetsMenuItem* widgets_menu_item_new (const gchar* _text,
                                        const gchar* _icon,
                                        const gchar* _tooltip);
WidgetsMenuItem* widgets_menu_item_construct (GType object_type,
                                              const gchar* _text,
                                              const gchar* _icon,
                                              const gchar* _tooltip);
static void __lambda75_ (WidgetsTrackRow* self);
static void ___lambda75__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda76_ (WidgetsTrackRow* self);
static void ___lambda76__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda77_ (Block13Data* _data13_);
void utils_set_next_track (Utils* self,
                           ObjectsTrack* track);
static void ___lambda77__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda78_ (Block13Data* _data13_);
void utils_set_last_track (Utils* self,
                           ObjectsTrack* track);
static void ___lambda78__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda79_ (Block13Data* _data13_);
void services_database_set_track_favorite (ServicesDatabase* self,
                                           ObjectsTrack* track,
                                           gint favorite);
static void ___lambda79__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda80_ (Block13Data* _data13_);
static void ___lambda80__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda81_ (WidgetsTrackRow* self);
static void ___lambda81__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda82_ (Block13Data* _data13_);
GType dialogs_track_editor_get_type (void) G_GNUC_CONST;
DialogsTrackEditor* dialogs_track_editor_new (ObjectsTrack* track);
DialogsTrackEditor* dialogs_track_editor_construct (GType object_type,
                                                    ObjectsTrack* track);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                        gpointer self);
static void ___lambda82__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda83_ (Block13Data* _data13_);
void services_database_remove_from_library (ServicesDatabase* self,
                                            ObjectsTrack* track);
static void ___lambda83__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda84_ (WidgetsTrackRow* self);
static void ___lambda84__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void __lambda85_ (Block13Data* _data13_);
gboolean services_database_remove_from_playlist (ServicesDatabase* self,
                                                 ObjectsTrack* track);
static void ___lambda85__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
static void widgets_track_row_set_track (WidgetsTrackRow* self,
                                  ObjectsTrack* value);
static GObject * widgets_track_row_constructor (GType type,
                                         guint n_construct_properties,
                                         GObjectConstructParam * construct_properties);
static Block14Data* block14_data_ref (Block14Data* _data14_);
static void block14_data_unref (void * _userdata_);
WidgetsCover* widgets_cover_new_from_file (const gchar* filepath,
                                           gint pixel_size,
                                           const gchar* type);
WidgetsCover* widgets_cover_construct_from_file (GType object_type,
                                                 const gchar* filepath,
                                                 gint pixel_size,
                                                 const gchar* type);
gchar* utils_get_formated_duration (Utils* self,
                                    guint64 duration);
GType services_player_get_type (void) G_GNUC_CONST;
ObjectsTrack* services_player_get_current_track (ServicesPlayer* self);
static void _widgets_track_row___lambda88_ (Block14Data* _data14_,
                                     ObjectsTrack* current_track);
static void __widgets_track_row___lambda88__services_player_current_track_changed (ServicesPlayer* _sender,
                                                                            ObjectsTrack* track,
                                                                            gpointer self);
static void _widgets_track_row___lambda89_ (WidgetsTrackRow* self,
                                     gint track_id);
static Block15Data* block15_data_ref (Block15Data* _data15_);
static void block15_data_unref (void * _userdata_);
static gboolean __lambda90_ (Block15Data* _data15_);
void widgets_cover_set_pixbuf (WidgetsCover* self,
                               GdkPixbuf* value);
static gboolean ___lambda90__gsource_func (gpointer self);
static void __widgets_track_row___lambda89__services_database_updated_track_cover (ServicesDatabase* _sender,
                                                                            gint track_id,
                                                                            gpointer self);
static void _widgets_track_row___lambda91_ (WidgetsTrackRow* self,
                                     ObjectsTrack* _track,
                                     gint favorite);
static void __widgets_track_row___lambda91__services_database_updated_track_favorite (ServicesDatabase* _sender,
                                                                               ObjectsTrack* track,
                                                                               gint favorite,
                                                                               gpointer self);
static gboolean _widgets_track_row___lambda92_ (Block14Data* _data14_,
                                         GdkEventCrossing* event);
static gboolean __widgets_track_row___lambda92__gtk_widget_enter_notify_event (GtkWidget* _sender,
                                                                        GdkEventCrossing* event,
                                                                        gpointer self);
static gboolean _widgets_track_row___lambda93_ (Block14Data* _data14_,
                                         GdkEventCrossing* event);
static gboolean __widgets_track_row___lambda93__gtk_widget_leave_notify_event (GtkWidget* _sender,
                                                                        GdkEventCrossing* event,
                                                                        gpointer self);
static gboolean _widgets_track_row___lambda94_ (WidgetsTrackRow* self,
                                         GtkWidget* sender,
                                         GdkEventButton* evt);
static gboolean __widgets_track_row___lambda94__gtk_widget_button_press_event (GtkWidget* _sender,
                                                                        GdkEventButton* event,
                                                                        gpointer self);
static void _widgets_track_row_activate_menu_gtk_button_clicked (GtkButton* _sender,
                                                          gpointer self);
static void _widgets_track_row___lambda95_ (Block14Data* _data14_);
static void __widgets_track_row___lambda95__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self);
static void _widgets_track_row___lambda96_ (WidgetsTrackRow* self,
                                     gint track_id);
static void __widgets_track_row___lambda96__services_database_removed_track (ServicesDatabase* _sender,
                                                                      gint id,
                                                                      gpointer self);
static void _widgets_track_row___lambda97_ (Block14Data* _data14_,
                                     ObjectsTrack* _track,
                                     gint favorite);
static void __widgets_track_row___lambda97__services_database_updated_track_favorite (ServicesDatabase* _sender,
                                                                               ObjectsTrack* track,
                                                                               gint favorite,
                                                                               gpointer self);
static void widgets_track_row_finalize (GObject * obj);
static void _vala_widgets_track_row_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec);
static void _vala_widgets_track_row_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec);


WidgetsTrackRow*
widgets_track_row_construct (GType object_type,
                             ObjectsTrack* track)
{
	WidgetsTrackRow * self = NULL;
	g_return_val_if_fail (track != NULL, NULL);
	self = (WidgetsTrackRow*) g_object_new (object_type, "track", track, NULL);
	return self;
}


WidgetsTrackRow*
widgets_track_row_new (ObjectsTrack* track)
{
	return widgets_track_row_construct (WIDGETS_TYPE_TRACK_ROW, track);
}


static void
___lambda86_ (WidgetsTrackRow* self)
{
	ObjectsPlaylist* new_playlist = NULL;
	ServicesDatabase* _tmp0_;
	ObjectsPlaylist* _tmp1_;
	ServicesDatabase* _tmp2_;
	ObjectsTrack* _tmp3_;
	gint _tmp4_;
	_tmp0_ = byte_database;
	_tmp1_ = services_database_create_new_playlist (_tmp0_);
	new_playlist = _tmp1_;
	_tmp2_ = byte_database;
	_tmp3_ = self->priv->_track;
	_tmp4_ = _tmp3_->id;
	services_database_insert_track_into_playlist (_tmp2_, new_playlist, _tmp4_);
	_g_object_unref0 (new_playlist);
}


static void
____lambda86__gtk_menu_item_activate (GtkMenuItem* _sender,
                                      gpointer self)
{
	___lambda86_ ((WidgetsTrackRow*) self);
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static Block12Data*
block12_data_ref (Block12Data* _data12_)
{
	g_atomic_int_inc (&_data12_->_ref_count_);
	return _data12_;
}


static void
block12_data_unref (void * _userdata_)
{
	Block12Data* _data12_;
	_data12_ = (Block12Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data12_->_ref_count_)) {
		WidgetsTrackRow* self;
		self = _data12_->self;
		_g_object_unref0 (_data12_->playlist);
		_g_object_unref0 (self);
		g_slice_free (Block12Data, _data12_);
	}
}


static void
_____lambda87_ (Block12Data* _data12_)
{
	WidgetsTrackRow* self;
	ServicesDatabase* _tmp0_;
	ObjectsPlaylist* _tmp1_;
	ObjectsTrack* _tmp2_;
	gint _tmp3_;
	self = _data12_->self;
	_tmp0_ = byte_database;
	_tmp1_ = _data12_->playlist;
	_tmp2_ = self->priv->_track;
	_tmp3_ = _tmp2_->id;
	services_database_insert_track_into_playlist (_tmp0_, _tmp1_, _tmp3_);
}


static void
______lambda87__gtk_menu_item_activate (GtkMenuItem* _sender,
                                        gpointer self)
{
	_____lambda87_ (self);
}


static void
widgets_track_row_activate_menu (WidgetsTrackRow* self)
{
	GtkMenu* _tmp0_;
	GtkMenu* _tmp2_;
	GList* _tmp3_;
	ServicesScan* _tmp5_;
	gboolean _tmp6_;
	GtkMenu* _tmp39_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->menu;
	if (_tmp0_ == NULL) {
		ObjectsTrack* _tmp1_;
		_tmp1_ = self->priv->_track;
		widgets_track_row_build_context_menu (self, _tmp1_);
	}
	_tmp2_ = self->priv->playlists;
	_tmp3_ = gtk_container_get_children ((GtkContainer*) _tmp2_);
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
		child_collection = _tmp3_;
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
			GtkWidget* child = NULL;
			child = (GtkWidget*) child_it->data;
			{
				GtkWidget* _tmp4_;
				_tmp4_ = child;
				gtk_widget_destroy (_tmp4_);
			}
		}
		(child_collection == NULL) ? NULL : (child_collection = (g_list_free (child_collection), NULL));
	}
	_tmp5_ = byte_scan_service;
	_tmp6_ = _tmp5_->is_sync;
	if (_tmp6_ == FALSE) {
		GeeArrayList* all_items = NULL;
		ServicesDatabase* _tmp7_;
		GeeArrayList* _tmp8_;
		GtkMenuItem* item = NULL;
		GtkMenuItem* _tmp9_;
		GtkMenuItem* _tmp10_;
		GtkStyleContext* _tmp11_;
		GtkMenuItem* _tmp12_;
		GtkStyleContext* _tmp13_;
		GtkMenuItem* _tmp14_;
		GtkMenu* _tmp15_;
		GtkMenuItem* _tmp16_;
		GtkMenu* _tmp38_;
		_tmp7_ = byte_database;
		_tmp8_ = services_database_get_all_playlists (_tmp7_);
		all_items = _tmp8_;
		_tmp9_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("Create New Playlist"));
		g_object_ref_sink (_tmp9_);
		item = _tmp9_;
		_tmp10_ = item;
		_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
		gtk_style_context_add_class (_tmp11_, "track-options");
		_tmp12_ = item;
		_tmp13_ = gtk_widget_get_style_context ((GtkWidget*) _tmp12_);
		gtk_style_context_add_class (_tmp13_, "css-item");
		_tmp14_ = item;
		g_signal_connect_object (_tmp14_, "activate", (GCallback) ____lambda86__gtk_menu_item_activate, self, 0);
		_tmp15_ = self->priv->playlists;
		_tmp16_ = item;
		gtk_container_add ((GtkContainer*) _tmp15_, (GtkWidget*) _tmp16_);
		{
			GeeArrayList* _playlist_list = NULL;
			GeeArrayList* _tmp17_;
			GeeArrayList* _tmp18_;
			gint _playlist_size = 0;
			GeeArrayList* _tmp19_;
			gint _tmp20_;
			gint _tmp21_;
			gint _playlist_index = 0;
			_tmp17_ = all_items;
			_tmp18_ = _g_object_ref0 (_tmp17_);
			_playlist_list = _tmp18_;
			_tmp19_ = _playlist_list;
			_tmp20_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp19_);
			_tmp21_ = _tmp20_;
			_playlist_size = _tmp21_;
			_playlist_index = -1;
			while (TRUE) {
				Block12Data* _data12_;
				gint _tmp22_;
				gint _tmp23_;
				gint _tmp24_;
				GeeArrayList* _tmp25_;
				gint _tmp26_;
				gpointer _tmp27_;
				ObjectsPlaylist* _tmp28_;
				const gchar* _tmp29_;
				GtkMenuItem* _tmp30_;
				GtkMenuItem* _tmp31_;
				GtkStyleContext* _tmp32_;
				GtkMenuItem* _tmp33_;
				GtkStyleContext* _tmp34_;
				GtkMenuItem* _tmp35_;
				GtkMenu* _tmp36_;
				GtkMenuItem* _tmp37_;
				_data12_ = g_slice_new0 (Block12Data);
				_data12_->_ref_count_ = 1;
				_data12_->self = g_object_ref (self);
				_tmp22_ = _playlist_index;
				_playlist_index = _tmp22_ + 1;
				_tmp23_ = _playlist_index;
				_tmp24_ = _playlist_size;
				if (!(_tmp23_ < _tmp24_)) {
					block12_data_unref (_data12_);
					_data12_ = NULL;
					break;
				}
				_tmp25_ = _playlist_list;
				_tmp26_ = _playlist_index;
				_tmp27_ = gee_abstract_list_get ((GeeAbstractList*) _tmp25_, _tmp26_);
				_data12_->playlist = (ObjectsPlaylist*) _tmp27_;
				_tmp28_ = _data12_->playlist;
				_tmp29_ = _tmp28_->title;
				_tmp30_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_tmp29_);
				g_object_ref_sink (_tmp30_);
				_g_object_unref0 (item);
				item = _tmp30_;
				_tmp31_ = item;
				_tmp32_ = gtk_widget_get_style_context ((GtkWidget*) _tmp31_);
				gtk_style_context_add_class (_tmp32_, "track-options");
				_tmp33_ = item;
				_tmp34_ = gtk_widget_get_style_context ((GtkWidget*) _tmp33_);
				gtk_style_context_add_class (_tmp34_, "css-item");
				_tmp35_ = item;
				g_signal_connect_data (_tmp35_, "activate", (GCallback) ______lambda87__gtk_menu_item_activate, block12_data_ref (_data12_), (GClosureNotify) block12_data_unref, 0);
				_tmp36_ = self->priv->playlists;
				_tmp37_ = item;
				gtk_container_add ((GtkContainer*) _tmp36_, (GtkWidget*) _tmp37_);
				block12_data_unref (_data12_);
				_data12_ = NULL;
			}
			_g_object_unref0 (_playlist_list);
		}
		_tmp38_ = self->priv->playlists;
		gtk_widget_show_all ((GtkWidget*) _tmp38_);
		_g_object_unref0 (item);
		_g_object_unref0 (all_items);
	}
	_tmp39_ = self->priv->menu;
	gtk_menu_popup_at_pointer (_tmp39_, NULL);
}


static Block13Data*
block13_data_ref (Block13Data* _data13_)
{
	g_atomic_int_inc (&_data13_->_ref_count_);
	return _data13_;
}


static void
block13_data_unref (void * _userdata_)
{
	Block13Data* _data13_;
	_data13_ = (Block13Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data13_->_ref_count_)) {
		WidgetsTrackRow* self;
		self = _data13_->self;
		_g_object_unref0 (_data13_->track);
		_g_object_unref0 (self);
		g_slice_free (Block13Data, _data13_);
	}
}


static void
__lambda75_ (WidgetsTrackRow* self)
{
	g_signal_emit_by_name ((GtkListBoxRow*) self, "activate");
}


static void
___lambda75__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda75_ ((WidgetsTrackRow*) self);
}


static void
__lambda76_ (WidgetsTrackRow* self)
{
	g_signal_emit_by_name ((GtkListBoxRow*) self, "activate");
}


static void
___lambda76__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda76_ ((WidgetsTrackRow*) self);
}


static void
__lambda77_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	Utils* _tmp0_;
	self = _data13_->self;
	_tmp0_ = byte_utils;
	utils_set_next_track (_tmp0_, _data13_->track);
}


static void
___lambda77__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda77_ (self);
}


static void
__lambda78_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	Utils* _tmp0_;
	self = _data13_->self;
	_tmp0_ = byte_utils;
	utils_set_last_track (_tmp0_, _data13_->track);
}


static void
___lambda78__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda78_ (self);
}


static void
__lambda79_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	ServicesScan* _tmp0_;
	gboolean _tmp1_;
	self = _data13_->self;
	_tmp0_ = byte_scan_service;
	_tmp1_ = _tmp0_->is_sync;
	if (_tmp1_ == FALSE) {
		ServicesDatabase* _tmp2_;
		_tmp2_ = byte_database;
		services_database_set_track_favorite (_tmp2_, _data13_->track, 1);
	}
}


static void
___lambda79__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda79_ (self);
}


static void
__lambda80_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	ServicesScan* _tmp0_;
	gboolean _tmp1_;
	self = _data13_->self;
	_tmp0_ = byte_scan_service;
	_tmp1_ = _tmp0_->is_sync;
	if (_tmp1_ == FALSE) {
		ServicesDatabase* _tmp2_;
		_tmp2_ = byte_database;
		services_database_set_track_favorite (_tmp2_, _data13_->track, 0);
	}
}


static void
___lambda80__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda80_ (self);
}


static void
__lambda81_ (WidgetsTrackRow* self)
{
}


static void
___lambda81__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda81_ ((WidgetsTrackRow*) self);
}


static void
_gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                   gpointer self)
{
	gtk_main_quit ();
}


static void
__lambda82_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	DialogsTrackEditor* editor_dialog = NULL;
	DialogsTrackEditor* _tmp0_;
	self = _data13_->self;
	_tmp0_ = dialogs_track_editor_new (_data13_->track);
	g_object_ref_sink (_tmp0_);
	editor_dialog = _tmp0_;
	g_signal_connect ((GtkWidget*) editor_dialog, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) editor_dialog);
	_g_object_unref0 (editor_dialog);
}


static void
___lambda82__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda82_ (self);
}


static void
__lambda83_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	GraniteMessageDialog* message_dialog = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	GraniteMessageDialog* _tmp3_;
	GraniteMessageDialog* _tmp4_;
	GtkButton* set_button = NULL;
	GtkButton* _tmp5_;
	GtkButton* _tmp6_;
	GtkStyleContext* _tmp7_;
	GraniteMessageDialog* _tmp8_;
	GtkButton* _tmp9_;
	GraniteMessageDialog* _tmp10_;
	GraniteMessageDialog* _tmp11_;
	GraniteMessageDialog* _tmp13_;
	self = _data13_->self;
	_tmp0_ = _data13_->track->title;
	_tmp1_ = g_strdup_printf (_ ("Are you sure you want to delete <b>%s</b> from your library?"), _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = granite_message_dialog_new_with_image_from_icon_name (_ ("Delete from library?"), _tmp2_, "dialog-warning", GTK_BUTTONS_CANCEL);
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	message_dialog = _tmp4_;
	_tmp5_ = (GtkButton*) gtk_button_new_with_label (_ ("Delete"));
	g_object_ref_sink (_tmp5_);
	set_button = _tmp5_;
	_tmp6_ = set_button;
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) _tmp6_);
	gtk_style_context_add_class (_tmp7_, GTK_STYLE_CLASS_DESTRUCTIVE_ACTION);
	_tmp8_ = message_dialog;
	_tmp9_ = set_button;
	gtk_dialog_add_action_widget ((GtkDialog*) _tmp8_, (GtkWidget*) _tmp9_, (gint) GTK_RESPONSE_ACCEPT);
	_tmp10_ = message_dialog;
	gtk_widget_show_all ((GtkWidget*) _tmp10_);
	_tmp11_ = message_dialog;
	if (gtk_dialog_run ((GtkDialog*) _tmp11_) == ((gint) GTK_RESPONSE_ACCEPT)) {
		ServicesDatabase* _tmp12_;
		_tmp12_ = byte_database;
		services_database_remove_from_library (_tmp12_, _data13_->track);
	}
	_tmp13_ = message_dialog;
	gtk_widget_destroy ((GtkWidget*) _tmp13_);
	_g_object_unref0 (set_button);
	_g_object_unref0 (message_dialog);
}


static void
___lambda83__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda83_ (self);
}


static void
__lambda84_ (WidgetsTrackRow* self)
{
}


static void
___lambda84__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda84_ ((WidgetsTrackRow*) self);
}


static void
__lambda85_ (Block13Data* _data13_)
{
	WidgetsTrackRow* self;
	ServicesDatabase* _tmp0_;
	self = _data13_->self;
	_tmp0_ = byte_database;
	if (services_database_remove_from_playlist (_tmp0_, _data13_->track)) {
		gtk_widget_destroy ((GtkWidget*) self);
	}
}


static void
___lambda85__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda85_ (self);
}


static void
widgets_track_row_build_context_menu (WidgetsTrackRow* self,
                                      ObjectsTrack* track)
{
	Block13Data* _data13_;
	ObjectsTrack* _tmp0_;
	GtkMenu* _tmp1_;
	GtkMenu* _tmp2_;
	GtkStyleContext* _tmp3_;
	GtkLabel* primary_label = NULL;
	const gchar* _tmp4_;
	GtkLabel* _tmp5_;
	GtkLabel* _tmp6_;
	GtkStyleContext* _tmp7_;
	GtkLabel* _tmp8_;
	GtkLabel* _tmp9_;
	GtkLabel* _tmp10_;
	GtkLabel* secondary_label = NULL;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	GtkLabel* _tmp15_;
	GtkLabel* _tmp16_;
	GtkLabel* _tmp17_;
	GtkLabel* _tmp18_;
	GtkLabel* _tmp19_;
	gchar* cover_path = NULL;
	Utils* _tmp20_;
	const gchar* _tmp21_;
	gint _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar* _tmp26_;
	GtkImage* image_cover = NULL;
	GtkImage* _tmp27_;
	GtkImage* _tmp28_;
	GtkImage* _tmp29_;
	GtkGrid* track_grid = NULL;
	GtkGrid* _tmp37_;
	GtkGrid* _tmp38_;
	GtkGrid* _tmp39_;
	GtkGrid* _tmp40_;
	GtkGrid* _tmp41_;
	GtkGrid* _tmp42_;
	GtkGrid* _tmp43_;
	GtkImage* _tmp44_;
	GtkGrid* _tmp45_;
	GtkLabel* _tmp46_;
	GtkGrid* _tmp47_;
	GtkLabel* _tmp48_;
	GtkMenuItem* track_menu = NULL;
	GtkMenuItem* _tmp49_;
	GtkMenuItem* _tmp50_;
	GtkStyleContext* _tmp51_;
	GtkMenuItem* _tmp52_;
	GtkStyleContext* _tmp53_;
	GtkMenuItem* _tmp54_;
	GtkMenuItem* _tmp55_;
	GtkGrid* _tmp56_;
	WidgetsMenuItem* play_menu = NULL;
	WidgetsMenuItem* _tmp57_;
	WidgetsMenuItem* play_next_menu = NULL;
	WidgetsMenuItem* _tmp58_;
	WidgetsMenuItem* play_last_menu = NULL;
	WidgetsMenuItem* _tmp59_;
	WidgetsMenuItem* add_playlist_menu = NULL;
	WidgetsMenuItem* _tmp60_;
	GtkMenu* _tmp61_;
	GtkMenu* _tmp62_;
	GtkStyleContext* _tmp63_;
	WidgetsMenuItem* _tmp64_;
	GtkMenu* _tmp65_;
	WidgetsMenuItem* edit_menu = NULL;
	WidgetsMenuItem* _tmp66_;
	WidgetsMenuItem* favorite_menu = NULL;
	WidgetsMenuItem* _tmp67_;
	WidgetsMenuItem* no_favorite_menu = NULL;
	WidgetsMenuItem* _tmp68_;
	WidgetsMenuItem* remove_db_menu = NULL;
	WidgetsMenuItem* _tmp69_;
	WidgetsMenuItem* remove_file_menu = NULL;
	WidgetsMenuItem* _tmp70_;
	WidgetsMenuItem* remove_playlist_menu = NULL;
	WidgetsMenuItem* _tmp71_;
	GtkMenu* _tmp72_;
	GtkMenuItem* _tmp73_;
	GtkMenu* _tmp74_;
	GtkSeparatorMenuItem* _tmp75_;
	GtkSeparatorMenuItem* _tmp76_;
	GtkMenu* _tmp77_;
	WidgetsMenuItem* _tmp78_;
	GtkMenu* _tmp79_;
	WidgetsMenuItem* _tmp80_;
	GtkMenu* _tmp81_;
	WidgetsMenuItem* _tmp82_;
	GtkMenu* _tmp83_;
	GtkSeparatorMenuItem* _tmp84_;
	GtkSeparatorMenuItem* _tmp85_;
	GtkMenu* _tmp86_;
	WidgetsMenuItem* _tmp87_;
	GtkMenu* _tmp88_;
	WidgetsMenuItem* _tmp89_;
	GtkMenu* _tmp90_;
	WidgetsMenuItem* _tmp91_;
	GtkMenu* _tmp92_;
	GtkSeparatorMenuItem* _tmp93_;
	GtkSeparatorMenuItem* _tmp94_;
	gint _tmp95_;
	GtkMenu* _tmp98_;
	WidgetsMenuItem* _tmp99_;
	GtkMenu* _tmp100_;
	GtkMenuItem* _tmp101_;
	WidgetsMenuItem* _tmp102_;
	WidgetsMenuItem* _tmp103_;
	WidgetsMenuItem* _tmp104_;
	WidgetsMenuItem* _tmp105_;
	WidgetsMenuItem* _tmp106_;
	WidgetsMenuItem* _tmp107_;
	WidgetsMenuItem* _tmp108_;
	WidgetsMenuItem* _tmp109_;
	WidgetsMenuItem* _tmp110_;
	WidgetsMenuItem* _tmp111_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (track != NULL);
	_data13_ = g_slice_new0 (Block13Data);
	_data13_->_ref_count_ = 1;
	_data13_->self = g_object_ref (self);
	_tmp0_ = _g_object_ref0 (track);
	_g_object_unref0 (_data13_->track);
	_data13_->track = _tmp0_;
	_tmp1_ = (GtkMenu*) gtk_menu_new ();
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->menu);
	self->priv->menu = _tmp1_;
	_tmp2_ = self->priv->menu;
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
	gtk_style_context_add_class (_tmp3_, "view");
	_tmp4_ = _data13_->track->title;
	_tmp5_ = (GtkLabel*) gtk_label_new (_tmp4_);
	g_object_ref_sink (_tmp5_);
	primary_label = _tmp5_;
	_tmp6_ = primary_label;
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) _tmp6_);
	gtk_style_context_add_class (_tmp7_, "font-bold");
	_tmp8_ = primary_label;
	gtk_label_set_ellipsize (_tmp8_, PANGO_ELLIPSIZE_END);
	_tmp9_ = primary_label;
	gtk_label_set_max_width_chars (_tmp9_, 25);
	_tmp10_ = primary_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp10_, GTK_ALIGN_START);
	_tmp11_ = _data13_->track->artist_name;
	_tmp12_ = _data13_->track->album_title;
	_tmp13_ = g_strdup_printf ("%s - %s", _tmp11_, _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = (GtkLabel*) gtk_label_new (_tmp14_);
	g_object_ref_sink (_tmp15_);
	_tmp16_ = _tmp15_;
	_g_free0 (_tmp14_);
	secondary_label = _tmp16_;
	_tmp17_ = secondary_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp17_, GTK_ALIGN_START);
	_tmp18_ = secondary_label;
	gtk_label_set_max_width_chars (_tmp18_, 25);
	_tmp19_ = secondary_label;
	gtk_label_set_ellipsize (_tmp19_, PANGO_ELLIPSIZE_END);
	_tmp20_ = byte_utils;
	_tmp21_ = _tmp20_->COVER_FOLDER;
	_tmp22_ = _data13_->track->id;
	_tmp23_ = g_strdup_printf ("track-%i.jpg", _tmp22_);
	_tmp24_ = _tmp23_;
	_tmp25_ = g_build_filename (_tmp21_, _tmp24_, NULL);
	_tmp26_ = _tmp25_;
	_g_free0 (_tmp24_);
	cover_path = _tmp26_;
	_tmp27_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp27_);
	image_cover = _tmp27_;
	_tmp28_ = image_cover;
	gtk_widget_set_halign ((GtkWidget*) _tmp28_, GTK_ALIGN_START);
	_tmp29_ = image_cover;
	gtk_widget_set_valign ((GtkWidget*) _tmp29_, GTK_ALIGN_START);
	{
		GdkPixbuf* _tmp30_ = NULL;
		const gchar* _tmp31_;
		GdkPixbuf* _tmp32_;
		GtkImage* _tmp33_;
		_tmp31_ = cover_path;
		_tmp32_ = gdk_pixbuf_new_from_file_at_size (_tmp31_, 38, 38, &_inner_error_);
		_tmp30_ = _tmp32_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch27_g_error;
		}
		_tmp33_ = image_cover;
		g_object_set (_tmp33_, "pixbuf", _tmp30_, NULL);
		_g_object_unref0 (_tmp30_);
	}
	goto __finally27;
	__catch27_g_error:
	{
		GError* e = NULL;
		GdkPixbuf* _tmp34_ = NULL;
		GdkPixbuf* _tmp35_;
		GtkImage* _tmp36_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp35_ = gdk_pixbuf_new_from_file_at_size ("/usr/share/com.github.alainm23.byte/track-default-cover.svg", 38, 38, &_inner_error_);
		_tmp34_ = _tmp35_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_error_free0 (e);
			goto __finally27;
		}
		_tmp36_ = image_cover;
		g_object_set (_tmp36_, "pixbuf", _tmp34_, NULL);
		_g_object_unref0 (_tmp34_);
		_g_error_free0 (e);
	}
	__finally27:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (image_cover);
		_g_free0 (cover_path);
		_g_object_unref0 (secondary_label);
		_g_object_unref0 (primary_label);
		block13_data_unref (_data13_);
		_data13_ = NULL;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp37_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp37_);
	track_grid = _tmp37_;
	_tmp38_ = track_grid;
	g_object_set ((GtkWidget*) _tmp38_, "width-request", 185, NULL);
	_tmp39_ = track_grid;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp39_, FALSE);
	_tmp40_ = track_grid;
	gtk_widget_set_halign ((GtkWidget*) _tmp40_, GTK_ALIGN_START);
	_tmp41_ = track_grid;
	gtk_widget_set_valign ((GtkWidget*) _tmp41_, GTK_ALIGN_CENTER);
	_tmp42_ = track_grid;
	gtk_grid_set_column_spacing (_tmp42_, 6);
	_tmp43_ = track_grid;
	_tmp44_ = image_cover;
	gtk_grid_attach (_tmp43_, (GtkWidget*) _tmp44_, 0, 0, 1, 2);
	_tmp45_ = track_grid;
	_tmp46_ = primary_label;
	gtk_grid_attach (_tmp45_, (GtkWidget*) _tmp46_, 1, 0, 1, 1);
	_tmp47_ = track_grid;
	_tmp48_ = secondary_label;
	gtk_grid_attach (_tmp47_, (GtkWidget*) _tmp48_, 1, 1, 1, 1);
	_tmp49_ = (GtkMenuItem*) gtk_menu_item_new ();
	g_object_ref_sink (_tmp49_);
	track_menu = _tmp49_;
	_tmp50_ = track_menu;
	_tmp51_ = gtk_widget_get_style_context ((GtkWidget*) _tmp50_);
	gtk_style_context_add_class (_tmp51_, "track-options");
	_tmp52_ = track_menu;
	_tmp53_ = gtk_widget_get_style_context ((GtkWidget*) _tmp52_);
	gtk_style_context_add_class (_tmp53_, "css-item");
	_tmp54_ = track_menu;
	gtk_menu_item_set_right_justified (_tmp54_, TRUE);
	_tmp55_ = track_menu;
	_tmp56_ = track_grid;
	gtk_container_add ((GtkContainer*) _tmp55_, (GtkWidget*) _tmp56_);
	_tmp57_ = widgets_menu_item_new (_ ("Play"), "media-playback-start-symbolic", _ ("Play"));
	g_object_ref_sink (_tmp57_);
	play_menu = _tmp57_;
	_tmp58_ = widgets_menu_item_new (_ ("Play Next"), "byte-play-next-symbolic", _ ("Play Next"));
	g_object_ref_sink (_tmp58_);
	play_next_menu = _tmp58_;
	_tmp59_ = widgets_menu_item_new (_ ("Play Later"), "byte-play-later-symbolic", _ ("Play Later"));
	g_object_ref_sink (_tmp59_);
	play_last_menu = _tmp59_;
	_tmp60_ = widgets_menu_item_new (_ ("Add to Playlist"), "zoom-in-symbolic", _ ("Add to Playlist"));
	g_object_ref_sink (_tmp60_);
	add_playlist_menu = _tmp60_;
	_tmp61_ = (GtkMenu*) gtk_menu_new ();
	g_object_ref_sink (_tmp61_);
	_g_object_unref0 (self->priv->playlists);
	self->priv->playlists = _tmp61_;
	_tmp62_ = self->priv->playlists;
	_tmp63_ = gtk_widget_get_style_context ((GtkWidget*) _tmp62_);
	gtk_style_context_add_class (_tmp63_, "view");
	_tmp64_ = add_playlist_menu;
	_tmp65_ = self->priv->playlists;
	gtk_menu_item_set_submenu ((GtkMenuItem*) _tmp64_, _tmp65_);
	_tmp66_ = widgets_menu_item_new (_ ("Edit Song Info…"), "edit-symbolic", _ ("Edit Song Info…"));
	g_object_ref_sink (_tmp66_);
	edit_menu = _tmp66_;
	_tmp67_ = widgets_menu_item_new (_ ("Love"), "byte-favorite-symbolic", _ ("Love"));
	g_object_ref_sink (_tmp67_);
	favorite_menu = _tmp67_;
	_tmp68_ = widgets_menu_item_new (_ ("Dislike"), "byte-no-favorite-symbolic", _ ("Dislike"));
	g_object_ref_sink (_tmp68_);
	no_favorite_menu = _tmp68_;
	_tmp69_ = widgets_menu_item_new (_ ("Delete from library"), "user-trash-symbolic", _ ("Delete from library"));
	g_object_ref_sink (_tmp69_);
	remove_db_menu = _tmp69_;
	_tmp70_ = widgets_menu_item_new (_ ("Delete from file"), "user-trash-symbolic", _ ("Delete from file"));
	g_object_ref_sink (_tmp70_);
	remove_file_menu = _tmp70_;
	_tmp71_ = widgets_menu_item_new (_ ("Remove from playlist"), "zoom-out-symbolic", _ ("Remove from playlist"));
	g_object_ref_sink (_tmp71_);
	remove_playlist_menu = _tmp71_;
	_tmp72_ = self->priv->menu;
	_tmp73_ = track_menu;
	gtk_container_add ((GtkContainer*) _tmp72_, (GtkWidget*) _tmp73_);
	_tmp74_ = self->priv->menu;
	_tmp75_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
	g_object_ref_sink (_tmp75_);
	_tmp76_ = _tmp75_;
	gtk_container_add ((GtkContainer*) _tmp74_, (GtkWidget*) _tmp76_);
	_g_object_unref0 (_tmp76_);
	_tmp77_ = self->priv->menu;
	_tmp78_ = play_menu;
	gtk_container_add ((GtkContainer*) _tmp77_, (GtkWidget*) _tmp78_);
	_tmp79_ = self->priv->menu;
	_tmp80_ = play_next_menu;
	gtk_container_add ((GtkContainer*) _tmp79_, (GtkWidget*) _tmp80_);
	_tmp81_ = self->priv->menu;
	_tmp82_ = play_last_menu;
	gtk_container_add ((GtkContainer*) _tmp81_, (GtkWidget*) _tmp82_);
	_tmp83_ = self->priv->menu;
	_tmp84_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
	g_object_ref_sink (_tmp84_);
	_tmp85_ = _tmp84_;
	gtk_container_add ((GtkContainer*) _tmp83_, (GtkWidget*) _tmp85_);
	_g_object_unref0 (_tmp85_);
	_tmp86_ = self->priv->menu;
	_tmp87_ = add_playlist_menu;
	gtk_container_add ((GtkContainer*) _tmp86_, (GtkWidget*) _tmp87_);
	_tmp88_ = self->priv->menu;
	_tmp89_ = favorite_menu;
	gtk_container_add ((GtkContainer*) _tmp88_, (GtkWidget*) _tmp89_);
	_tmp90_ = self->priv->menu;
	_tmp91_ = no_favorite_menu;
	gtk_container_add ((GtkContainer*) _tmp90_, (GtkWidget*) _tmp91_);
	_tmp92_ = self->priv->menu;
	_tmp93_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
	g_object_ref_sink (_tmp93_);
	_tmp94_ = _tmp93_;
	gtk_container_add ((GtkContainer*) _tmp92_, (GtkWidget*) _tmp94_);
	_g_object_unref0 (_tmp94_);
	_tmp95_ = _data13_->track->playlist;
	if (_tmp95_ != 0) {
		GtkMenu* _tmp96_;
		WidgetsMenuItem* _tmp97_;
		_tmp96_ = self->priv->menu;
		_tmp97_ = remove_playlist_menu;
		gtk_container_add ((GtkContainer*) _tmp96_, (GtkWidget*) _tmp97_);
	}
	_tmp98_ = self->priv->menu;
	_tmp99_ = remove_db_menu;
	gtk_container_add ((GtkContainer*) _tmp98_, (GtkWidget*) _tmp99_);
	_tmp100_ = self->priv->menu;
	gtk_widget_show_all ((GtkWidget*) _tmp100_);
	_tmp101_ = track_menu;
	g_signal_connect_object (_tmp101_, "activate", (GCallback) ___lambda75__gtk_menu_item_activate, self, 0);
	_tmp102_ = play_menu;
	g_signal_connect_object ((GtkMenuItem*) _tmp102_, "activate", (GCallback) ___lambda76__gtk_menu_item_activate, self, 0);
	_tmp103_ = play_next_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp103_, "activate", (GCallback) ___lambda77__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_tmp104_ = play_last_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp104_, "activate", (GCallback) ___lambda78__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_tmp105_ = favorite_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp105_, "activate", (GCallback) ___lambda79__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_tmp106_ = no_favorite_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp106_, "activate", (GCallback) ___lambda80__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_tmp107_ = add_playlist_menu;
	g_signal_connect_object ((GtkMenuItem*) _tmp107_, "activate", (GCallback) ___lambda81__gtk_menu_item_activate, self, 0);
	_tmp108_ = edit_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp108_, "activate", (GCallback) ___lambda82__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_tmp109_ = remove_db_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp109_, "activate", (GCallback) ___lambda83__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_tmp110_ = remove_file_menu;
	g_signal_connect_object ((GtkMenuItem*) _tmp110_, "activate", (GCallback) ___lambda84__gtk_menu_item_activate, self, 0);
	_tmp111_ = remove_playlist_menu;
	g_signal_connect_data ((GtkMenuItem*) _tmp111_, "activate", (GCallback) ___lambda85__gtk_menu_item_activate, block13_data_ref (_data13_), (GClosureNotify) block13_data_unref, 0);
	_g_object_unref0 (remove_playlist_menu);
	_g_object_unref0 (remove_file_menu);
	_g_object_unref0 (remove_db_menu);
	_g_object_unref0 (no_favorite_menu);
	_g_object_unref0 (favorite_menu);
	_g_object_unref0 (edit_menu);
	_g_object_unref0 (add_playlist_menu);
	_g_object_unref0 (play_last_menu);
	_g_object_unref0 (play_next_menu);
	_g_object_unref0 (play_menu);
	_g_object_unref0 (track_menu);
	_g_object_unref0 (track_grid);
	_g_object_unref0 (image_cover);
	_g_free0 (cover_path);
	_g_object_unref0 (secondary_label);
	_g_object_unref0 (primary_label);
	block13_data_unref (_data13_);
	_data13_ = NULL;
}


ObjectsTrack*
widgets_track_row_get_track (WidgetsTrackRow* self)
{
	ObjectsTrack* result;
	ObjectsTrack* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_track;
	result = _tmp0_;
	return result;
}


static void
widgets_track_row_set_track (WidgetsTrackRow* self,
                             ObjectsTrack* value)
{
	g_return_if_fail (self != NULL);
	if (widgets_track_row_get_track (self) != value) {
		ObjectsTrack* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_track);
		self->priv->_track = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, widgets_track_row_properties[WIDGETS_TRACK_ROW_TRACK_PROPERTY]);
	}
}


static Block14Data*
block14_data_ref (Block14Data* _data14_)
{
	g_atomic_int_inc (&_data14_->_ref_count_);
	return _data14_;
}


static void
block14_data_unref (void * _userdata_)
{
	Block14Data* _data14_;
	_data14_ = (Block14Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data14_->_ref_count_)) {
		WidgetsTrackRow* self;
		self = _data14_->self;
		_g_object_unref0 (_data14_->main_grid);
		_g_object_unref0 (_data14_->icon_no_favorite);
		_g_object_unref0 (_data14_->icon_favorite);
		_g_object_unref0 (_data14_->options_stack);
		_g_object_unref0 (_data14_->playing_revealer);
		_g_object_unref0 (self);
		g_slice_free (Block14Data, _data14_);
	}
}


static void
_widgets_track_row___lambda88_ (Block14Data* _data14_,
                                ObjectsTrack* current_track)
{
	WidgetsTrackRow* self;
	ObjectsTrack* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GError * _inner_error_ = NULL;
	self = _data14_->self;
	_tmp0_ = self->priv->_track;
	_tmp1_ = _tmp0_->id;
	_tmp2_ = current_track->id;
	if (_tmp1_ == _tmp2_) {
		GtkRevealer* _tmp3_;
		GtkGrid* _tmp4_;
		GtkStyleContext* _tmp5_;
		_tmp3_ = _data14_->playing_revealer;
		gtk_revealer_set_reveal_child (_tmp3_, TRUE);
		_tmp4_ = _data14_->main_grid;
		_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
		gtk_style_context_add_class (_tmp5_, "label-color-primary");
		{
			gtk_widget_grab_focus ((GtkWidget*) self);
		}
		goto __finally28;
		__catch28_g_error:
		{
			GError* e = NULL;
			FILE* _tmp6_;
			GError* _tmp7_;
			const gchar* _tmp8_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp6_ = stderr;
			_tmp7_ = e;
			_tmp8_ = _tmp7_->message;
			fprintf (_tmp6_, "Error setting default avatar icon: %s ", _tmp8_);
			_g_error_free0 (e);
		}
		__finally28:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	} else {
		GtkRevealer* _tmp9_;
		GtkGrid* _tmp10_;
		GtkStyleContext* _tmp11_;
		_tmp9_ = _data14_->playing_revealer;
		gtk_revealer_set_reveal_child (_tmp9_, FALSE);
		_tmp10_ = _data14_->main_grid;
		_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
		gtk_style_context_remove_class (_tmp11_, "label-color-primary");
	}
}


static void
__widgets_track_row___lambda88__services_player_current_track_changed (ServicesPlayer* _sender,
                                                                       ObjectsTrack* track,
                                                                       gpointer self)
{
	_widgets_track_row___lambda88_ (self, track);
}


static Block15Data*
block15_data_ref (Block15Data* _data15_)
{
	g_atomic_int_inc (&_data15_->_ref_count_);
	return _data15_;
}


static void
block15_data_unref (void * _userdata_)
{
	Block15Data* _data15_;
	_data15_ = (Block15Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data15_->_ref_count_)) {
		WidgetsTrackRow* self;
		self = _data15_->self;
		_g_object_unref0 (self);
		g_slice_free (Block15Data, _data15_);
	}
}


static gboolean
__lambda90_ (Block15Data* _data15_)
{
	WidgetsTrackRow* self;
	gboolean result = FALSE;
	ObjectsTrack* _tmp0_;
	gint _tmp1_;
	GError * _inner_error_ = NULL;
	self = _data15_->self;
	_tmp0_ = self->priv->_track;
	_tmp1_ = _tmp0_->id;
	if (_data15_->track_id == _tmp1_) {
		{
			GdkPixbuf* _tmp2_ = NULL;
			Utils* _tmp3_;
			const gchar* _tmp4_;
			gchar* _tmp5_;
			gchar* _tmp6_;
			gchar* _tmp7_;
			gchar* _tmp8_;
			GdkPixbuf* _tmp9_;
			GdkPixbuf* _tmp10_;
			WidgetsCover* _tmp11_;
			_tmp3_ = byte_utils;
			_tmp4_ = _tmp3_->COVER_FOLDER;
			_tmp5_ = g_strdup_printf ("track-%i.jpg", _data15_->track_id);
			_tmp6_ = _tmp5_;
			_tmp7_ = g_build_filename (_tmp4_, _tmp6_, NULL);
			_tmp8_ = _tmp7_;
			_tmp9_ = gdk_pixbuf_new_from_file_at_size (_tmp8_, 32, 32, &_inner_error_);
			_tmp10_ = _tmp9_;
			_g_free0 (_tmp8_);
			_g_free0 (_tmp6_);
			_tmp2_ = _tmp10_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch29_g_error;
			}
			_tmp11_ = self->priv->image_cover;
			widgets_cover_set_pixbuf (_tmp11_, _tmp2_);
			_g_object_unref0 (_tmp2_);
		}
		goto __finally29;
		__catch29_g_error:
		{
			GError* e = NULL;
			FILE* _tmp12_;
			GError* _tmp13_;
			const gchar* _tmp14_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp12_ = stderr;
			_tmp13_ = e;
			_tmp14_ = _tmp13_->message;
			fprintf (_tmp12_, "Error setting default avatar icon: %s ", _tmp14_);
			_g_error_free0 (e);
		}
		__finally29:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			gboolean _tmp15_ = FALSE;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return _tmp15_;
		}
	}
	result = FALSE;
	return result;
}


static gboolean
___lambda90__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda90_ (self);
	return result;
}


static void
_widgets_track_row___lambda89_ (WidgetsTrackRow* self,
                                gint track_id)
{
	Block15Data* _data15_;
	_data15_ = g_slice_new0 (Block15Data);
	_data15_->_ref_count_ = 1;
	_data15_->self = g_object_ref (self);
	_data15_->track_id = track_id;
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda90__gsource_func, block15_data_ref (_data15_), block15_data_unref);
	block15_data_unref (_data15_);
	_data15_ = NULL;
}


static void
__widgets_track_row___lambda89__services_database_updated_track_cover (ServicesDatabase* _sender,
                                                                       gint track_id,
                                                                       gpointer self)
{
	_widgets_track_row___lambda89_ ((WidgetsTrackRow*) self, track_id);
}


static void
_widgets_track_row___lambda91_ (WidgetsTrackRow* self,
                                ObjectsTrack* _track,
                                gint favorite)
{
	ObjectsTrack* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	g_return_if_fail (_track != NULL);
	_tmp0_ = self->priv->_track;
	_tmp1_ = _tmp0_->id;
	_tmp2_ = _track->id;
	if (_tmp1_ == _tmp2_) {
		ObjectsTrack* _tmp3_;
		_tmp3_ = self->priv->_track;
		_tmp3_->is_favorite = favorite;
	}
}


static void
__widgets_track_row___lambda91__services_database_updated_track_favorite (ServicesDatabase* _sender,
                                                                          ObjectsTrack* track,
                                                                          gint favorite,
                                                                          gpointer self)
{
	_widgets_track_row___lambda91_ ((WidgetsTrackRow*) self, track, favorite);
}


static gboolean
_widgets_track_row___lambda92_ (Block14Data* _data14_,
                                GdkEventCrossing* event)
{
	WidgetsTrackRow* self;
	gboolean result = FALSE;
	GtkStack* _tmp0_;
	self = _data14_->self;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = _data14_->options_stack;
	gtk_stack_set_visible_child_name (_tmp0_, "options_button");
	result = FALSE;
	return result;
}


static gboolean
__widgets_track_row___lambda92__gtk_widget_enter_notify_event (GtkWidget* _sender,
                                                               GdkEventCrossing* event,
                                                               gpointer self)
{
	gboolean result;
	result = _widgets_track_row___lambda92_ (self, event);
	return result;
}


static gboolean
_widgets_track_row___lambda93_ (Block14Data* _data14_,
                                GdkEventCrossing* event)
{
	WidgetsTrackRow* self;
	gboolean result = FALSE;
	GdkNotifyType _tmp0_;
	GtkStack* _tmp1_;
	self = _data14_->self;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = event->detail;
	if (_tmp0_ == GDK_NOTIFY_INFERIOR) {
		result = FALSE;
		return result;
	}
	_tmp1_ = _data14_->options_stack;
	gtk_stack_set_visible_child_name (_tmp1_, "duration_label");
	result = FALSE;
	return result;
}


static gboolean
__widgets_track_row___lambda93__gtk_widget_leave_notify_event (GtkWidget* _sender,
                                                               GdkEventCrossing* event,
                                                               gpointer self)
{
	gboolean result;
	result = _widgets_track_row___lambda93_ (self, event);
	return result;
}


static gboolean
_widgets_track_row___lambda94_ (WidgetsTrackRow* self,
                                GtkWidget* sender,
                                GdkEventButton* evt)
{
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GdkEventType _tmp1_;
	g_return_val_if_fail (sender != NULL, FALSE);
	g_return_val_if_fail (evt != NULL, FALSE);
	_tmp1_ = evt->type;
	if (_tmp1_ == GDK_BUTTON_PRESS) {
		guint _tmp2_;
		_tmp2_ = evt->button;
		_tmp0_ = _tmp2_ == ((guint) 3);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		widgets_track_row_activate_menu (self);
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


static gboolean
__widgets_track_row___lambda94__gtk_widget_button_press_event (GtkWidget* _sender,
                                                               GdkEventButton* event,
                                                               gpointer self)
{
	gboolean result;
	result = _widgets_track_row___lambda94_ ((WidgetsTrackRow*) self, _sender, event);
	return result;
}


static void
_widgets_track_row_activate_menu_gtk_button_clicked (GtkButton* _sender,
                                                     gpointer self)
{
	widgets_track_row_activate_menu ((WidgetsTrackRow*) self);
}


static void
_widgets_track_row___lambda95_ (Block14Data* _data14_)
{
	WidgetsTrackRow* self;
	GtkButton* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
	GtkImage* _tmp3_;
	self = _data14_->self;
	_tmp0_ = self->priv->favorite_button;
	_tmp1_ = gtk_button_get_image (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _data14_->icon_favorite;
	if (_tmp2_ == G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, gtk_widget_get_type (), GtkWidget)) {
		GtkButton* _tmp4_;
		GtkImage* _tmp5_;
		ServicesDatabase* _tmp6_;
		ObjectsTrack* _tmp7_;
		_tmp4_ = self->priv->favorite_button;
		_tmp5_ = _data14_->icon_no_favorite;
		gtk_button_set_image (_tmp4_, (GtkWidget*) _tmp5_);
		_tmp6_ = byte_database;
		_tmp7_ = self->priv->_track;
		services_database_set_track_favorite (_tmp6_, _tmp7_, 0);
	} else {
		GtkButton* _tmp8_;
		GtkImage* _tmp9_;
		ServicesDatabase* _tmp10_;
		ObjectsTrack* _tmp11_;
		_tmp8_ = self->priv->favorite_button;
		_tmp9_ = _data14_->icon_favorite;
		gtk_button_set_image (_tmp8_, (GtkWidget*) _tmp9_);
		_tmp10_ = byte_database;
		_tmp11_ = self->priv->_track;
		services_database_set_track_favorite (_tmp10_, _tmp11_, 1);
	}
}


static void
__widgets_track_row___lambda95__gtk_button_clicked (GtkButton* _sender,
                                                    gpointer self)
{
	_widgets_track_row___lambda95_ (self);
}


static void
_widgets_track_row___lambda96_ (WidgetsTrackRow* self,
                                gint track_id)
{
	ObjectsTrack* _tmp0_;
	gint _tmp1_;
	_tmp0_ = self->priv->_track;
	_tmp1_ = _tmp0_->id;
	if (track_id == _tmp1_) {
		gtk_widget_destroy ((GtkWidget*) self);
	}
}


static void
__widgets_track_row___lambda96__services_database_removed_track (ServicesDatabase* _sender,
                                                                 gint id,
                                                                 gpointer self)
{
	_widgets_track_row___lambda96_ ((WidgetsTrackRow*) self, id);
}


static void
_widgets_track_row___lambda97_ (Block14Data* _data14_,
                                ObjectsTrack* _track,
                                gint favorite)
{
	WidgetsTrackRow* self;
	ObjectsTrack* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	self = _data14_->self;
	g_return_if_fail (_track != NULL);
	_tmp0_ = self->priv->_track;
	_tmp1_ = _tmp0_->id;
	_tmp2_ = _track->id;
	if (_tmp1_ == _tmp2_) {
		if (favorite == 0) {
			GtkButton* _tmp3_;
			GtkImage* _tmp4_;
			_tmp3_ = self->priv->favorite_button;
			_tmp4_ = _data14_->icon_no_favorite;
			gtk_button_set_image (_tmp3_, (GtkWidget*) _tmp4_);
		} else {
			GtkButton* _tmp5_;
			GtkImage* _tmp6_;
			_tmp5_ = self->priv->favorite_button;
			_tmp6_ = _data14_->icon_favorite;
			gtk_button_set_image (_tmp5_, (GtkWidget*) _tmp6_);
		}
	}
}


static void
__widgets_track_row___lambda97__services_database_updated_track_favorite (ServicesDatabase* _sender,
                                                                          ObjectsTrack* track,
                                                                          gint favorite,
                                                                          gpointer self)
{
	_widgets_track_row___lambda97_ (self, track, favorite);
}


static GObject *
widgets_track_row_constructor (GType type,
                               guint n_construct_properties,
                               GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	WidgetsTrackRow * self;
	Block14Data* _data14_;
	GtkStyleContext* _tmp0_;
	GtkImage* playing_icon = NULL;
	GtkImage* _tmp1_;
	GtkImage* _tmp2_;
	GThemedIcon* _tmp3_;
	GThemedIcon* _tmp4_;
	GtkImage* _tmp5_;
	GtkStyleContext* _tmp6_;
	GtkImage* _tmp7_;
	GtkRevealer* _tmp8_;
	GtkRevealer* _tmp9_;
	GtkRevealer* _tmp10_;
	GtkRevealer* _tmp11_;
	GtkRevealer* _tmp12_;
	GtkImage* _tmp13_;
	GtkRevealer* _tmp14_;
	ObjectsTrack* _tmp15_;
	const gchar* _tmp16_;
	GtkLabel* _tmp17_;
	GtkLabel* _tmp18_;
	GtkStyleContext* _tmp19_;
	GtkLabel* _tmp20_;
	GtkLabel* _tmp21_;
	GtkLabel* _tmp22_;
	GtkLabel* _tmp23_;
	ObjectsTrack* _tmp24_;
	const gchar* _tmp25_;
	GtkLabel* _tmp26_;
	GtkLabel* _tmp27_;
	GtkStyleContext* _tmp28_;
	GtkLabel* _tmp29_;
	GtkLabel* _tmp30_;
	GtkLabel* _tmp31_;
	GtkLabel* _tmp32_;
	GtkLabel* _tmp33_;
	Utils* _tmp34_;
	const gchar* _tmp35_;
	ObjectsTrack* _tmp36_;
	gint _tmp37_;
	gchar* _tmp38_;
	gchar* _tmp39_;
	gchar* _tmp40_;
	gchar* _tmp41_;
	WidgetsCover* _tmp42_;
	WidgetsCover* _tmp43_;
	WidgetsCover* _tmp44_;
	Utils* _tmp45_;
	ObjectsTrack* _tmp46_;
	guint64 _tmp47_;
	gchar* _tmp48_;
	gchar* _tmp49_;
	GtkLabel* _tmp50_;
	GtkButton* options_button = NULL;
	GtkButton* _tmp51_;
	GtkButton* _tmp52_;
	GtkButton* _tmp53_;
	GtkButton* _tmp54_;
	GtkButton* _tmp55_;
	GtkStyleContext* _tmp56_;
	GtkButton* _tmp57_;
	GtkStyleContext* _tmp58_;
	GtkButton* _tmp59_;
	GtkStyleContext* _tmp60_;
	GtkButton* _tmp61_;
	GtkStyleContext* _tmp62_;
	GtkStack* _tmp63_;
	GtkStack* _tmp64_;
	GtkStack* _tmp65_;
	GtkLabel* _tmp66_;
	GtkStack* _tmp67_;
	GtkButton* _tmp68_;
	GtkImage* _tmp69_;
	GtkImage* _tmp70_;
	GThemedIcon* _tmp71_;
	GThemedIcon* _tmp72_;
	GtkImage* _tmp73_;
	GtkImage* _tmp74_;
	GtkImage* _tmp75_;
	GThemedIcon* _tmp76_;
	GThemedIcon* _tmp77_;
	GtkImage* _tmp78_;
	GtkButton* _tmp79_;
	GtkButton* _tmp80_;
	GtkStyleContext* _tmp81_;
	GtkButton* _tmp82_;
	GtkStyleContext* _tmp83_;
	GtkButton* _tmp84_;
	GtkButton* _tmp85_;
	ObjectsTrack* _tmp86_;
	gint _tmp87_;
	GtkGrid* right_grid = NULL;
	GtkGrid* _tmp92_;
	GtkGrid* _tmp93_;
	GtkGrid* _tmp94_;
	GtkGrid* _tmp95_;
	GtkGrid* _tmp96_;
	GtkGrid* _tmp97_;
	GtkGrid* _tmp98_;
	GtkButton* _tmp99_;
	GtkGrid* _tmp100_;
	GtkStack* _tmp101_;
	GtkOverlay* overlay = NULL;
	GtkOverlay* _tmp102_;
	GtkOverlay* _tmp103_;
	GtkOverlay* _tmp104_;
	GtkOverlay* _tmp105_;
	GtkOverlay* _tmp106_;
	GtkRevealer* _tmp107_;
	GtkOverlay* _tmp108_;
	WidgetsCover* _tmp109_;
	GtkGrid* _tmp110_;
	GtkGrid* _tmp111_;
	GtkGrid* _tmp112_;
	GtkGrid* _tmp113_;
	GtkGrid* _tmp114_;
	GtkGrid* _tmp115_;
	GtkOverlay* _tmp116_;
	GtkGrid* _tmp117_;
	GtkLabel* _tmp118_;
	GtkGrid* _tmp119_;
	GtkLabel* _tmp120_;
	GtkGrid* _tmp121_;
	GtkGrid* _tmp122_;
	GtkSeparator* separator = NULL;
	GtkSeparator* _tmp123_;
	GtkSeparator* _tmp124_;
	GtkSeparator* _tmp125_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp126_;
	GtkGrid* _tmp127_;
	GtkGrid* _tmp128_;
	GtkGrid* _tmp129_;
	GtkGrid* _tmp130_;
	GtkGrid* _tmp131_;
	GtkSeparator* _tmp132_;
	GtkEventBox* eventbox = NULL;
	GtkEventBox* _tmp133_;
	GtkEventBox* _tmp134_;
	GtkEventBox* _tmp135_;
	GtkGrid* _tmp136_;
	GtkEventBox* _tmp137_;
	gboolean _tmp138_ = FALSE;
	ServicesPlayer* _tmp139_;
	ObjectsTrack* _tmp140_;
	ObjectsTrack* _tmp141_;
	ServicesPlayer* _tmp151_;
	ServicesDatabase* _tmp152_;
	ServicesDatabase* _tmp153_;
	GtkEventBox* _tmp154_;
	GtkEventBox* _tmp155_;
	GtkButton* _tmp156_;
	GtkButton* _tmp157_;
	ServicesDatabase* _tmp158_;
	ServicesDatabase* _tmp159_;
	parent_class = G_OBJECT_CLASS (widgets_track_row_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRow);
	_data14_ = g_slice_new0 (Block14Data);
	_data14_->_ref_count_ = 1;
	_data14_->self = g_object_ref (self);
	_tmp0_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_class (_tmp0_, "track-row");
	_tmp1_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp1_);
	playing_icon = _tmp1_;
	_tmp2_ = playing_icon;
	_tmp3_ = (GThemedIcon*) g_themed_icon_new ("audio-volume-medium-symbolic");
	_tmp4_ = _tmp3_;
	g_object_set (_tmp2_, "gicon", (GIcon*) _tmp4_, NULL);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = playing_icon;
	_tmp6_ = gtk_widget_get_style_context ((GtkWidget*) _tmp5_);
	gtk_style_context_add_class (_tmp6_, "playing-ani-color");
	_tmp7_ = playing_icon;
	gtk_image_set_pixel_size (_tmp7_, 12);
	_tmp8_ = (GtkRevealer*) gtk_revealer_new ();
	g_object_ref_sink (_tmp8_);
	_data14_->playing_revealer = _tmp8_;
	_tmp9_ = _data14_->playing_revealer;
	gtk_widget_set_halign ((GtkWidget*) _tmp9_, GTK_ALIGN_CENTER);
	_tmp10_ = _data14_->playing_revealer;
	gtk_widget_set_valign ((GtkWidget*) _tmp10_, GTK_ALIGN_CENTER);
	_tmp11_ = _data14_->playing_revealer;
	gtk_revealer_set_transition_type (_tmp11_, GTK_REVEALER_TRANSITION_TYPE_CROSSFADE);
	_tmp12_ = _data14_->playing_revealer;
	_tmp13_ = playing_icon;
	gtk_container_add ((GtkContainer*) _tmp12_, (GtkWidget*) _tmp13_);
	_tmp14_ = _data14_->playing_revealer;
	gtk_revealer_set_reveal_child (_tmp14_, FALSE);
	_tmp15_ = self->priv->_track;
	_tmp16_ = _tmp15_->title;
	_tmp17_ = (GtkLabel*) gtk_label_new (_tmp16_);
	g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->primary_label);
	self->priv->primary_label = _tmp17_;
	_tmp18_ = self->priv->primary_label;
	_tmp19_ = gtk_widget_get_style_context ((GtkWidget*) _tmp18_);
	gtk_style_context_add_class (_tmp19_, "font-bold");
	_tmp20_ = self->priv->primary_label;
	gtk_label_set_ellipsize (_tmp20_, PANGO_ELLIPSIZE_END);
	_tmp21_ = self->priv->primary_label;
	gtk_label_set_max_width_chars (_tmp21_, 40);
	_tmp22_ = self->priv->primary_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp22_, GTK_ALIGN_START);
	_tmp23_ = self->priv->primary_label;
	gtk_widget_set_valign ((GtkWidget*) _tmp23_, GTK_ALIGN_END);
	_tmp24_ = self->priv->_track;
	_tmp25_ = _tmp24_->artist_name;
	_tmp26_ = (GtkLabel*) gtk_label_new (_tmp25_);
	g_object_ref_sink (_tmp26_);
	_g_object_unref0 (self->priv->secondary_label);
	self->priv->secondary_label = _tmp26_;
	_tmp27_ = self->priv->secondary_label;
	_tmp28_ = gtk_widget_get_style_context ((GtkWidget*) _tmp27_);
	gtk_style_context_add_class (_tmp28_, "secondary_label");
	_tmp29_ = self->priv->secondary_label;
	gtk_label_set_use_markup (_tmp29_, TRUE);
	_tmp30_ = self->priv->secondary_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp30_, GTK_ALIGN_START);
	_tmp31_ = self->priv->secondary_label;
	gtk_widget_set_valign ((GtkWidget*) _tmp31_, GTK_ALIGN_START);
	_tmp32_ = self->priv->secondary_label;
	gtk_label_set_max_width_chars (_tmp32_, 40);
	_tmp33_ = self->priv->secondary_label;
	gtk_label_set_ellipsize (_tmp33_, PANGO_ELLIPSIZE_END);
	_tmp34_ = byte_utils;
	_tmp35_ = _tmp34_->COVER_FOLDER;
	_tmp36_ = self->priv->_track;
	_tmp37_ = _tmp36_->id;
	_tmp38_ = g_strdup_printf ("track-%i.jpg", _tmp37_);
	_tmp39_ = _tmp38_;
	_tmp40_ = g_build_filename (_tmp35_, _tmp39_, NULL);
	_tmp41_ = _tmp40_;
	_tmp42_ = widgets_cover_new_from_file (_tmp41_, 32, "track");
	g_object_ref_sink (_tmp42_);
	_g_object_unref0 (self->priv->image_cover);
	self->priv->image_cover = _tmp42_;
	_g_free0 (_tmp41_);
	_g_free0 (_tmp39_);
	_tmp43_ = self->priv->image_cover;
	gtk_widget_set_halign ((GtkWidget*) _tmp43_, GTK_ALIGN_START);
	_tmp44_ = self->priv->image_cover;
	gtk_widget_set_valign ((GtkWidget*) _tmp44_, GTK_ALIGN_START);
	_tmp45_ = byte_utils;
	_tmp46_ = self->priv->_track;
	_tmp47_ = _tmp46_->duration;
	_tmp48_ = utils_get_formated_duration (_tmp45_, _tmp47_);
	_tmp49_ = _tmp48_;
	_tmp50_ = (GtkLabel*) gtk_label_new (_tmp49_);
	g_object_ref_sink (_tmp50_);
	_g_object_unref0 (self->priv->duration_label);
	self->priv->duration_label = _tmp50_;
	_g_free0 (_tmp49_);
	_tmp51_ = (GtkButton*) gtk_button_new_from_icon_name ("view-more-horizontal-symbolic", (GtkIconSize) GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp51_);
	options_button = _tmp51_;
	_tmp52_ = options_button;
	gtk_widget_set_valign ((GtkWidget*) _tmp52_, GTK_ALIGN_CENTER);
	_tmp53_ = options_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp53_, FALSE);
	_tmp54_ = options_button;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp54_, _ ("Options"));
	_tmp55_ = options_button;
	_tmp56_ = gtk_widget_get_style_context ((GtkWidget*) _tmp55_);
	gtk_style_context_add_class (_tmp56_, GTK_STYLE_CLASS_FLAT);
	_tmp57_ = options_button;
	_tmp58_ = gtk_widget_get_style_context ((GtkWidget*) _tmp57_);
	gtk_style_context_add_class (_tmp58_, "options-button");
	_tmp59_ = options_button;
	_tmp60_ = gtk_widget_get_style_context ((GtkWidget*) _tmp59_);
	gtk_style_context_add_class (_tmp60_, "button-color");
	_tmp61_ = options_button;
	_tmp62_ = gtk_widget_get_style_context ((GtkWidget*) _tmp61_);
	gtk_style_context_remove_class (_tmp62_, "button");
	_tmp63_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp63_);
	_data14_->options_stack = _tmp63_;
	_tmp64_ = _data14_->options_stack;
	gtk_stack_set_transition_type (_tmp64_, GTK_STACK_TRANSITION_TYPE_CROSSFADE);
	_tmp65_ = _data14_->options_stack;
	_tmp66_ = self->priv->duration_label;
	gtk_stack_add_named (_tmp65_, (GtkWidget*) _tmp66_, "duration_label");
	_tmp67_ = _data14_->options_stack;
	_tmp68_ = options_button;
	gtk_stack_add_named (_tmp67_, (GtkWidget*) _tmp68_, "options_button");
	_tmp69_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp69_);
	_data14_->icon_favorite = _tmp69_;
	_tmp70_ = _data14_->icon_favorite;
	_tmp71_ = (GThemedIcon*) g_themed_icon_new ("byte-favorite-symbolic");
	_tmp72_ = _tmp71_;
	g_object_set (_tmp70_, "gicon", (GIcon*) _tmp72_, NULL);
	_g_object_unref0 (_tmp72_);
	_tmp73_ = _data14_->icon_favorite;
	gtk_image_set_pixel_size (_tmp73_, 14);
	_tmp74_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp74_);
	_data14_->icon_no_favorite = _tmp74_;
	_tmp75_ = _data14_->icon_no_favorite;
	_tmp76_ = (GThemedIcon*) g_themed_icon_new ("byte-no-favorite-symbolic");
	_tmp77_ = _tmp76_;
	g_object_set (_tmp75_, "gicon", (GIcon*) _tmp77_, NULL);
	_g_object_unref0 (_tmp77_);
	_tmp78_ = _data14_->icon_no_favorite;
	gtk_image_set_pixel_size (_tmp78_, 14);
	_tmp79_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp79_);
	_g_object_unref0 (self->priv->favorite_button);
	self->priv->favorite_button = _tmp79_;
	_tmp80_ = self->priv->favorite_button;
	_tmp81_ = gtk_widget_get_style_context ((GtkWidget*) _tmp80_);
	gtk_style_context_add_class (_tmp81_, GTK_STYLE_CLASS_FLAT);
	_tmp82_ = self->priv->favorite_button;
	_tmp83_ = gtk_widget_get_style_context ((GtkWidget*) _tmp82_);
	gtk_style_context_add_class (_tmp83_, "button-color");
	_tmp84_ = self->priv->favorite_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp84_, FALSE);
	_tmp85_ = self->priv->favorite_button;
	gtk_widget_set_valign ((GtkWidget*) _tmp85_, GTK_ALIGN_CENTER);
	_tmp86_ = self->priv->_track;
	_tmp87_ = _tmp86_->is_favorite;
	if (_tmp87_ == 0) {
		GtkButton* _tmp88_;
		GtkImage* _tmp89_;
		_tmp88_ = self->priv->favorite_button;
		_tmp89_ = _data14_->icon_no_favorite;
		gtk_button_set_image (_tmp88_, (GtkWidget*) _tmp89_);
	} else {
		GtkButton* _tmp90_;
		GtkImage* _tmp91_;
		_tmp90_ = self->priv->favorite_button;
		_tmp91_ = _data14_->icon_favorite;
		gtk_button_set_image (_tmp90_, (GtkWidget*) _tmp91_);
	}
	_tmp92_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp92_);
	right_grid = _tmp92_;
	_tmp93_ = right_grid;
	gtk_widget_set_halign ((GtkWidget*) _tmp93_, GTK_ALIGN_END);
	_tmp94_ = right_grid;
	gtk_widget_set_valign ((GtkWidget*) _tmp94_, GTK_ALIGN_CENTER);
	_tmp95_ = right_grid;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp95_, TRUE);
	_tmp96_ = right_grid;
	gtk_grid_set_column_spacing (_tmp96_, 6);
	_tmp97_ = right_grid;
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp97_, GTK_ORIENTATION_HORIZONTAL);
	_tmp98_ = right_grid;
	_tmp99_ = self->priv->favorite_button;
	gtk_container_add ((GtkContainer*) _tmp98_, (GtkWidget*) _tmp99_);
	_tmp100_ = right_grid;
	_tmp101_ = _data14_->options_stack;
	gtk_container_add ((GtkContainer*) _tmp100_, (GtkWidget*) _tmp101_);
	_tmp102_ = (GtkOverlay*) gtk_overlay_new ();
	g_object_ref_sink (_tmp102_);
	overlay = _tmp102_;
	_tmp103_ = overlay;
	gtk_widget_set_halign ((GtkWidget*) _tmp103_, GTK_ALIGN_START);
	_tmp104_ = overlay;
	gtk_widget_set_valign ((GtkWidget*) _tmp104_, GTK_ALIGN_START);
	_tmp105_ = overlay;
	gtk_widget_set_margin_top ((GtkWidget*) _tmp105_, 1);
	_tmp106_ = overlay;
	_tmp107_ = _data14_->playing_revealer;
	gtk_overlay_add_overlay (_tmp106_, (GtkWidget*) _tmp107_);
	_tmp108_ = overlay;
	_tmp109_ = self->priv->image_cover;
	gtk_container_add ((GtkContainer*) _tmp108_, (GtkWidget*) _tmp109_);
	_tmp110_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp110_);
	_data14_->main_grid = _tmp110_;
	_tmp111_ = _data14_->main_grid;
	gtk_widget_set_margin_top ((GtkWidget*) _tmp111_, 1);
	_tmp112_ = _data14_->main_grid;
	gtk_widget_set_margin_start ((GtkWidget*) _tmp112_, 3);
	_tmp113_ = _data14_->main_grid;
	gtk_widget_set_margin_end ((GtkWidget*) _tmp113_, 9);
	_tmp114_ = _data14_->main_grid;
	gtk_grid_set_column_spacing (_tmp114_, 3);
	_tmp115_ = _data14_->main_grid;
	_tmp116_ = overlay;
	gtk_grid_attach (_tmp115_, (GtkWidget*) _tmp116_, 0, 0, 1, 2);
	_tmp117_ = _data14_->main_grid;
	_tmp118_ = self->priv->primary_label;
	gtk_grid_attach (_tmp117_, (GtkWidget*) _tmp118_, 1, 0, 1, 1);
	_tmp119_ = _data14_->main_grid;
	_tmp120_ = self->priv->secondary_label;
	gtk_grid_attach (_tmp119_, (GtkWidget*) _tmp120_, 1, 1, 1, 1);
	_tmp121_ = _data14_->main_grid;
	_tmp122_ = right_grid;
	gtk_grid_attach (_tmp121_, (GtkWidget*) _tmp122_, 2, 0, 2, 2);
	_tmp123_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
	g_object_ref_sink (_tmp123_);
	separator = _tmp123_;
	_tmp124_ = separator;
	gtk_widget_set_margin_start ((GtkWidget*) _tmp124_, 48);
	_tmp125_ = separator;
	gtk_widget_set_margin_top ((GtkWidget*) _tmp125_, 1);
	_tmp126_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp126_);
	grid = _tmp126_;
	_tmp127_ = grid;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp127_, TRUE);
	_tmp128_ = grid;
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp128_, GTK_ORIENTATION_VERTICAL);
	_tmp129_ = grid;
	_tmp130_ = _data14_->main_grid;
	gtk_container_add ((GtkContainer*) _tmp129_, (GtkWidget*) _tmp130_);
	_tmp131_ = grid;
	_tmp132_ = separator;
	gtk_container_add ((GtkContainer*) _tmp131_, (GtkWidget*) _tmp132_);
	_tmp133_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp133_);
	eventbox = _tmp133_;
	_tmp134_ = eventbox;
	gtk_widget_add_events ((GtkWidget*) _tmp134_, (gint) (GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK));
	_tmp135_ = eventbox;
	_tmp136_ = grid;
	gtk_container_add ((GtkContainer*) _tmp135_, (GtkWidget*) _tmp136_);
	_tmp137_ = eventbox;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp137_);
	_tmp139_ = byte_player;
	_tmp140_ = services_player_get_current_track (_tmp139_);
	_tmp141_ = _tmp140_;
	if (_tmp141_ != NULL) {
		ObjectsTrack* _tmp142_;
		gint _tmp143_;
		ServicesPlayer* _tmp144_;
		ObjectsTrack* _tmp145_;
		ObjectsTrack* _tmp146_;
		gint _tmp147_;
		_tmp142_ = self->priv->_track;
		_tmp143_ = _tmp142_->id;
		_tmp144_ = byte_player;
		_tmp145_ = services_player_get_current_track (_tmp144_);
		_tmp146_ = _tmp145_;
		_tmp147_ = _tmp146_->id;
		_tmp138_ = _tmp143_ == _tmp147_;
	} else {
		_tmp138_ = FALSE;
	}
	if (_tmp138_) {
		GtkRevealer* _tmp148_;
		GtkGrid* _tmp149_;
		GtkStyleContext* _tmp150_;
		_tmp148_ = _data14_->playing_revealer;
		gtk_revealer_set_reveal_child (_tmp148_, TRUE);
		_tmp149_ = _data14_->main_grid;
		_tmp150_ = gtk_widget_get_style_context ((GtkWidget*) _tmp149_);
		gtk_style_context_add_class (_tmp150_, "label-color-primary");
	}
	_tmp151_ = byte_player;
	g_signal_connect_data (_tmp151_, "current-track-changed", (GCallback) __widgets_track_row___lambda88__services_player_current_track_changed, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_tmp152_ = byte_database;
	g_signal_connect_object (_tmp152_, "updated-track-cover", (GCallback) __widgets_track_row___lambda89__services_database_updated_track_cover, self, 0);
	_tmp153_ = byte_database;
	g_signal_connect_object (_tmp153_, "updated-track-favorite", (GCallback) __widgets_track_row___lambda91__services_database_updated_track_favorite, self, 0);
	_tmp154_ = eventbox;
	g_signal_connect_data ((GtkWidget*) _tmp154_, "enter-notify-event", (GCallback) __widgets_track_row___lambda92__gtk_widget_enter_notify_event, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_tmp155_ = eventbox;
	g_signal_connect_data ((GtkWidget*) _tmp155_, "leave-notify-event", (GCallback) __widgets_track_row___lambda93__gtk_widget_leave_notify_event, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) __widgets_track_row___lambda94__gtk_widget_button_press_event, self, 0);
	_tmp156_ = options_button;
	g_signal_connect_object (_tmp156_, "clicked", (GCallback) _widgets_track_row_activate_menu_gtk_button_clicked, self, 0);
	_tmp157_ = self->priv->favorite_button;
	g_signal_connect_data (_tmp157_, "clicked", (GCallback) __widgets_track_row___lambda95__gtk_button_clicked, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_tmp158_ = byte_database;
	g_signal_connect_object (_tmp158_, "removed-track", (GCallback) __widgets_track_row___lambda96__services_database_removed_track, self, 0);
	_tmp159_ = byte_database;
	g_signal_connect_data (_tmp159_, "updated-track-favorite", (GCallback) __widgets_track_row___lambda97__services_database_updated_track_favorite, block14_data_ref (_data14_), (GClosureNotify) block14_data_unref, 0);
	_g_object_unref0 (eventbox);
	_g_object_unref0 (grid);
	_g_object_unref0 (separator);
	_g_object_unref0 (overlay);
	_g_object_unref0 (right_grid);
	_g_object_unref0 (options_button);
	_g_object_unref0 (playing_icon);
	block14_data_unref (_data14_);
	_data14_ = NULL;
	return obj;
}


static void
widgets_track_row_class_init (WidgetsTrackRowClass * klass)
{
	widgets_track_row_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (WidgetsTrackRowPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_widgets_track_row_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_widgets_track_row_set_property;
	G_OBJECT_CLASS (klass)->constructor = widgets_track_row_constructor;
	G_OBJECT_CLASS (klass)->finalize = widgets_track_row_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), WIDGETS_TRACK_ROW_TRACK_PROPERTY, widgets_track_row_properties[WIDGETS_TRACK_ROW_TRACK_PROPERTY] = g_param_spec_object ("track", "track", "track", OBJECTS_TYPE_TRACK, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}


static void
widgets_track_row_instance_init (WidgetsTrackRow * self)
{
	self->priv = WIDGETS_TRACK_ROW_GET_PRIVATE (self);
	self->priv->menu = NULL;
}


static void
widgets_track_row_finalize (GObject * obj)
{
	WidgetsTrackRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRow);
	_g_object_unref0 (self->priv->_track);
	_g_object_unref0 (self->priv->primary_label);
	_g_object_unref0 (self->priv->secondary_label);
	_g_object_unref0 (self->priv->duration_label);
	_g_object_unref0 (self->priv->favorite_button);
	_g_object_unref0 (self->priv->playlists);
	_g_object_unref0 (self->priv->menu);
	_g_object_unref0 (self->priv->image_cover);
	G_OBJECT_CLASS (widgets_track_row_parent_class)->finalize (obj);
}


GType
widgets_track_row_get_type (void)
{
	static volatile gsize widgets_track_row_type_id__volatile = 0;
	if (g_once_init_enter (&widgets_track_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WidgetsTrackRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) widgets_track_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WidgetsTrackRow), 0, (GInstanceInitFunc) widgets_track_row_instance_init, NULL };
		GType widgets_track_row_type_id;
		widgets_track_row_type_id = g_type_register_static (gtk_list_box_row_get_type (), "WidgetsTrackRow", &g_define_type_info, 0);
		g_once_init_leave (&widgets_track_row_type_id__volatile, widgets_track_row_type_id);
	}
	return widgets_track_row_type_id__volatile;
}


static void
_vala_widgets_track_row_get_property (GObject * object,
                                      guint property_id,
                                      GValue * value,
                                      GParamSpec * pspec)
{
	WidgetsTrackRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRow);
	switch (property_id) {
		case WIDGETS_TRACK_ROW_TRACK_PROPERTY:
		g_value_set_object (value, widgets_track_row_get_track (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void
_vala_widgets_track_row_set_property (GObject * object,
                                      guint property_id,
                                      const GValue * value,
                                      GParamSpec * pspec)
{
	WidgetsTrackRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WIDGETS_TYPE_TRACK_ROW, WidgetsTrackRow);
	switch (property_id) {
		case WIDGETS_TRACK_ROW_TRACK_PROPERTY:
		widgets_track_row_set_track (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



