id: com.PrivatusAI.PrivatusAI
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: privatusai

finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --share=network
  - --socket=pulseaudio
  - --device=all

modules:
  - name: privatusai
    buildsystem: simple
    sources:
      - type: dir
        path: app_bundle
      - type: dir
        path: flatpak_file
    build-commands:
      - mkdir -p /app/privatusai-bundle
      
      - cp -a privatusai /app/privatusai-bundle/
      - cp -a data /app/privatusai-bundle/
      - cp -a lib /app/privatusai-bundle/
      
      - mkdir -p /app/bin
      
      - echo '#!/bin/sh' > /app/bin/privatusai
      - echo 'exec /app/privatusai-bundle/privatusai "$@"' >> /app/bin/privatusai
      - chmod +x /app/bin/privatusai
      
      - mkdir -p /app/share/applications
      - mkdir -p /app/share/icons/hicolor/scalable/apps
      
      - install -Dm644 com.PrivatusAI.PrivatusAI.desktop /app/share/applications/com.PrivatusAI.PrivatusAI.desktop
      - install -Dm644 icon.png /app/share/icons/hicolor/scalable/apps/com.PrivatusAI.PrivatusAI.png