--- a/Makefile	2017-07-25 13:44:57.000000000 -0500
+++ b/Makefile	2025-01-12 08:11:00.340111086 -0500
@@ -15,7 +15,11 @@
 #
 # LIBS settings for 64 bit Linux/unix systems.
 #
-export LIBS=-static -L../lib -lsdp -llapack -lblas -lm
+PREFIX ?= /usr/local
+FF=$(find /usr/lib -name libgomp.so)
+LIBSYS=$(dirname $FF)
+
+export LIBS=-L/app/plugins/Aditional1/lib -L/app/plugins/Aditional1/lib64 ../lib/libsdp.a -llapack -lblas -lm
 #
 #
 # On most systems, this should handle everything.
@@ -38,11 +42,11 @@
 #
 
 install:
-	cp -f solver/csdp /usr/local/bin
-	cp -f theta/theta /usr/local/bin
-	cp -f theta/graphtoprob /usr/local/bin
-	cp -f theta/complement /usr/local/bin
-	cp -f theta/rand_graph /usr/local/bin
+	cp -f solver/csdp ${PREFIX}/bin
+	cp -f theta/theta ${PREFIX}/bin
+	cp -f theta/graphtoprob ${PREFIX}/bin
+	cp -f theta/complement ${PREFIX}/bin
+	cp -f theta/rand_graph ${PREFIX}/bin
 
 #
 # Clean out all of the directories.
