name: Crash Report
labels: ["bug"]
description: 'Please use this template if you experienced a crash or freeze'
body:
  - type: input
    attributes:
      label: yuzu Version
      description: 'The version of yuzu you were using when this crash happened (can be found on the title bar)'
  - type: textarea
    attributes:
      label: Description
      description: 'Please describe what you were doing before and when this crash happened'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Reproduction Certainty
      description: 'Can you always reproduce this crash? Does this crash happens very often or happens rarely?'
      multiple: false
      options:
        - Always
        - Not always, but often
        - Sometimes
        - Rarely
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Information
      description: 'If possible, install `inxi`, run `inxi -v3` on your system and paste the output here'
      render: 'bash session'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Logs and Backtraces
      description: |
        If possible, please attach the yuzu log file and/or debugger backtrace file here ([how to obtain them](http://y2nlvhmmk5jnsvechppxnbyzmmv3vbl7dvzn6ltwcdbpgxixp3clkgqd.onion/torzu-emu/onion.torzu_emu.torzu/src/branch/master#obtaining-a-debugger-trace-as-the-crash-happens))
        Please **avoid pasting the log** into this box. Instead, use the __file upload__ function to attach the file.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Remarks
      description: 'Do you have something notable to mention? Anything that will give us more context?'
      placeholder: |
        - Does this issue also happen in the AppImage version?
        - Did you notice any anomalies prior to the crash?
        - Does this crash happen in older Flatpak versions?
    validations:
      required: false
