#!/bin/bash

set -e

cd /app/config

if test -f /app/server/dhcpgui.conf.bak ; then
  # During creation of the flatpak, we made a backup of the configuration and a link.
  echo "I will try to allow the user to edit the configuration."
  if ! test -f dhcpgui.conf ; then
    echo "No configuration detected. Creating a new one."
    ls -la /app/server/ /app/config/
    if ! cp /app/server/dhcpgui.conf.bak dhcpgui.conf; then
      echo "Could not create configuration file for user to edit."
      echo "Switching to static configuration that cannot be edited."
      rm /app/server/dhcpgui.conf
      cp /app/server/dhcpgui.conf.bak /app/server/dhcpgui.conf
    fi
  fi
else
  echo "The user cannot edit the configuration."
  cd /tmp/
fi

python3 /app/server/dhcpgui.pyw
