#!/bin/bash
APPPATH=/app/extra

## Start the binary directly and avoid the upstream launcher script. It's pointless here because inside a Flatpak the environment is always the same.
FIRESTORMBIN=$APPPATH/bin/do-not-directly-run-firestorm-bin
PARAMS="--set FSLinuxEnableWin32VoiceProxy TRUE --setdefault FSLinuxEnableWin32VoiceProxy TRUE --set CacheLocation $XDG_CACHE_HOME/firestorm --set NewCacheLocation $XDG_CACHE_HOME/firestorm --set ExternalEditor /usr/bin/xdg-open"

## The non-deferred render does not work under Xwayland, this makes sure it will always be disabled.
if [ ! -z $WAYLAND_DISPLAY ]; then
  PARAMS+=" --set RenderDeferred TRUE"
fi

function prepareDiscord {
  ## Discord RPC support
  for i in {0..9}; do
    test -S $XDG_RUNTIME_DIR/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
    ## Discord RPC wont accept PIDs below 10 for unknown reasons, so bump the pids.
    true
  done
}

## Avoids an often-buggy X feature that doesn't really benefit us anyway.
export SDL_VIDEO_X11_DGAMOUSE=0
# This makes the tmpdir something the host can resolve, this is only used for editing scripts in an external editor.
export TMPDIR=$XDG_CACHE_HOME/tmp
export WINEPREFIX=$XDG_DATA_HOME/wine

cd $APPPATH

if [ -n "$1" ]; then
  if gdbus introspect -e -d com.secondlife.ViewerAppAPIService -o /com/secondlife/ViewerAppAPI; then
    gdbus call  -e -d com.secondlife.ViewerAppAPIService  -o /com/secondlife/ViewerAppAPI  -m com.secondlife.ViewerAppAPI.GoSLURL "$1"
  else
    prepareDiscord
    $FIRESTORMBIN $PARAMS -url "$1"
  fi
else
  prepareDiscord
  $FIRESTORMBIN $PARAMS
fi
