#!/usr/bin/env bash

FEATURES="UseSkiaRenderer"
TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-tv.plex.Plexamp}"
declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist)

if [[ $XDG_SESSION_TYPE == "wayland" ]]
then    
    if [[ -e "$XDG_RUNTIME_DIR/${WAYLAND_SOCKET}" ]]
    then
      echo "Wayland socket is available, running natively on Wayland."
      echo "To disable, remove the --socket=wayland permission."
      FLAGS+=(--ozone-platform=wayland)
    else
      echo "Wayland socket not available, running through Xwayland."
    fi
    if [[ -c /dev/nvidia0 ]]
    then
      echo "Using NVIDIA on Wayland, applying workaround"
      FLAGS+=(--disable-gpu-sandbox)
    fi
fi

FLAGS+=(--enable-features="${FEATURES}")
echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/plexamp/Plexamp "${FLAGS[@]}" "$@"