#!/usr/bin/env bash

# Set FEATURES to what goes after --enable-features; for example, UseSkiaRenderer,WebRTCPipeWireCapturer,etc,etc will then get turned into --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,etc,etc.
FEATURES="UseSkiaRenderer"
TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-xyz.armcord.ArmCord}"
declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization)

if [[ "${XDG_SESSION_TYPE,,}" = "wayland" ]]; then

    # Just your normal NVIDIA things
    if [[ -c /dev/nvidia0 ]]; then
        echo "Using NVIDIA on Wayland, applying workaround"
        FLAGS+=(--disable-gpu-sandbox)
    fi

fi

FLAGS+=(--enable-features="${FEATURES}")
echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
zypak-wrapper /app/bin/armcord/armcord "${FLAGS[@]}" "$@"
