#!/bin/sh
set -eu
: "${XDG_DATA_HOME:?Flatpak XDG_DATA_HOME is required}"
: "${XDG_RUNTIME_DIR:?Flatpak XDG_RUNTIME_DIR is required}"
export XDG_STATE_HOME="$XDG_DATA_HOME/state"
export LIGHTTABLE_INSTANCE_DIR="$XDG_RUNTIME_DIR/app/app.lighttable.LightTable/instances"
export PYTHONNOUSERSITE=1
exec /app/LightTable/bin/lighttable "$@"
