#!/bin/bash

set -x

export WINEARCH=win64

if ! [ -e "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Image-Line/FL Studio 20/FL64.exe" ] ; then
	source /app/bin/flstudio-installer
	if [[ $? != 0 ]] ; then
		echo "Installation failed, abort."
		exit 1
	fi
fi

wine64 "C:/Program Files (x86)/Image-Line/FL Studio 20/FL64.exe"
