#!/bin/bash

if [ -z "$WINEPREFIX" ] ; then
	echo "No wine prefix set or is empty, abort."
	exit 1
fi

if [ -f "${WINEPREFIX}/dosdevices/c:/Program Files (x86)/Image-Line/FL Studio 20/FL64.exe" ] ; then
	echo "This prefix already has an exisiting 'flstudio' install at ${WINEPREFIX}"
	echo "In order to install 'flstudio' you must move or delete the current prefix."
	exit 1
fi

echo "Setting-up wine prefix..."
wineboot

if [ ! -f "${XDG_CACHE_HOME}/flstudio_win.exe" ]
then
	echo "Downloading installer..."
	curl -L --progress-bar --output "${XDG_CACHE_HOME}/flstudio_win.exe" "https://support.image-line.com/action/redirect/flstudio20_win_installer" || (echo "Download failed."; exit 1)
fi

echo "Launching application installer... (press next on all options)"
wine64 "${XDG_CACHE_HOME}/flstudio_win.exe"

echo "Installer finished"
