/* Album.c generated by valac 0.40.11, the Vala compiler
 * generated from Album.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define OBJECTS_TYPE_ALBUM (objects_album_get_type ())
#define OBJECTS_ALBUM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OBJECTS_TYPE_ALBUM, ObjectsAlbum))
#define OBJECTS_ALBUM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OBJECTS_TYPE_ALBUM, ObjectsAlbumClass))
#define OBJECTS_IS_ALBUM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OBJECTS_TYPE_ALBUM))
#define OBJECTS_IS_ALBUM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OBJECTS_TYPE_ALBUM))
#define OBJECTS_ALBUM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OBJECTS_TYPE_ALBUM, ObjectsAlbumClass))

typedef struct _ObjectsAlbum ObjectsAlbum;
typedef struct _ObjectsAlbumClass ObjectsAlbumClass;
typedef struct _ObjectsAlbumPrivate ObjectsAlbumPrivate;
enum  {
	OBJECTS_ALBUM_0_PROPERTY,
	OBJECTS_ALBUM_NUM_PROPERTIES
};
static GParamSpec* objects_album_properties[OBJECTS_ALBUM_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ObjectsAlbum {
	GObject parent_instance;
	ObjectsAlbumPrivate * priv;
	gint id;
	gint artist_id;
	gchar* artist_name;
	gint year;
	gchar* title;
	gchar* genre;
};

struct _ObjectsAlbumClass {
	GObjectClass parent_class;
};


static gpointer objects_album_parent_class = NULL;

GType objects_album_get_type (void) G_GNUC_CONST;
ObjectsAlbum* objects_album_new (gint id,
                                 gint artist_id,
                                 const gchar* artist_name,
                                 gint year,
                                 const gchar* title,
                                 const gchar* genre);
ObjectsAlbum* objects_album_construct (GType object_type,
                                       gint id,
                                       gint artist_id,
                                       const gchar* artist_name,
                                       gint year,
                                       const gchar* title,
                                       const gchar* genre);
static void objects_album_finalize (GObject * obj);


ObjectsAlbum*
objects_album_construct (GType object_type,
                         gint id,
                         gint artist_id,
                         const gchar* artist_name,
                         gint year,
                         const gchar* title,
                         const gchar* genre)
{
	ObjectsAlbum * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (artist_name != NULL, NULL);
	g_return_val_if_fail (title != NULL, NULL);
	g_return_val_if_fail (genre != NULL, NULL);
	self = (ObjectsAlbum*) g_object_new (object_type, NULL);
	self->id = id;
	self->artist_id = artist_id;
	self->year = year;
	_tmp0_ = g_strdup (genre);
	_g_free0 (self->genre);
	self->genre = _tmp0_;
	_tmp1_ = g_strdup (genre);
	_g_free0 (self->genre);
	self->genre = _tmp1_;
	return self;
}


ObjectsAlbum*
objects_album_new (gint id,
                   gint artist_id,
                   const gchar* artist_name,
                   gint year,
                   const gchar* title,
                   const gchar* genre)
{
	return objects_album_construct (OBJECTS_TYPE_ALBUM, id, artist_id, artist_name, year, title, genre);
}


static void
objects_album_class_init (ObjectsAlbumClass * klass)
{
	objects_album_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = objects_album_finalize;
}


static void
objects_album_instance_init (ObjectsAlbum * self)
{
}


static void
objects_album_finalize (GObject * obj)
{
	ObjectsAlbum * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, OBJECTS_TYPE_ALBUM, ObjectsAlbum);
	_g_free0 (self->artist_name);
	_g_free0 (self->title);
	_g_free0 (self->genre);
	G_OBJECT_CLASS (objects_album_parent_class)->finalize (obj);
}


GType
objects_album_get_type (void)
{
	static volatile gsize objects_album_type_id__volatile = 0;
	if (g_once_init_enter (&objects_album_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ObjectsAlbumClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) objects_album_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ObjectsAlbum), 0, (GInstanceInitFunc) objects_album_instance_init, NULL };
		GType objects_album_type_id;
		objects_album_type_id = g_type_register_static (G_TYPE_OBJECT, "ObjectsAlbum", &g_define_type_info, 0);
		g_once_init_leave (&objects_album_type_id__volatile, objects_album_type_id);
	}
	return objects_album_type_id__volatile;
}



