#!/bin/bash

[ $# -eq 1 ] || { echo missing module name; exit 1; }

_mod=$1

# remove fedc
jq --indent 4 --join-output 'del(.sources[0]."x-checker-data")' ${_mod}-fedc.json > ${_mod}.json
rm ${_mod}-fedc.json
