#!/bin/bash

[ $# -eq 1 ] || { echo missing module name; exit 1; }

_mod=$(basename $1)

if [ "$_mod" == "$1" ]; then
  pushd $_mod
else
  pushd $1
fi
# add fedc
jq --indent 4 --join-output --argjson fedc "$(<fedc.json)" '.sources[0] += $fedc' ${_mod}.json > ${_mod}-fedc.json

# look for an update
flatpak-external-data-checker --edit-only ${_mod}-fedc.json

# disable fedc
jq --indent 4 --join-output 'del(.sources[0]."x-checker-data")' ${_mod}-fedc.json > ${_mod}.json
rm ${_mod}-fedc.json

popd
