#!/bin/bash
echo "opts: $@"
PY_VER=python$(python3 -c 'import sys; print(sys.version[:3])')
sip-install \
  --target-dir ${FLATPAK_DEST}/lib/${PY_VER}/site-packages \
  --scripts-dir ${FLATPAK_DEST}/bin \
  --build-dir ./build \
  --jobs ${FLATPAK_BUILDER_N_JOBS} \
  --debug \
  --verbose $@
