name: auto-merge

on:
  issue_comment:
  schedule:
    - cron: '14 12 * * *'
  workflow_dispatch: {}

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ (github.event.issue && github.event.issue.pull_request) || !github.event.issue }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - run: npm install execa@5
      - uses: actions/github-script@v6
        name: Check and Merge
        id: check-changes
        with:
          script: |
            const execa = require("execa");
            const mergebot = require('./.github/workflows/merge.js');
            const branch = await mergebot.checkChanges(github, context);
            if (branch)
              await mergebot.mergeChanges(branch, execa);
