name: 'Build image for merge workflow'

on:
  push:
    branches: master
    paths:
      - ".github/actions/merge/*"
      - .github/workflows/merge.yml
      - .github/workflows/build-merge.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .github/actions/merge
          file: .github/actions/merge/Dockerfile
          tags: ghcr.io/flathub/actions/merge:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
