name: "Publish flatpak to Github releases"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
          manifest-path: io.github.ja2_stracciatella.JA2-Stracciatella.yaml
      - uses: actions/upload-artifact@v3
        with:
          name: io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
          path: ./io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
  release:
    runs-on: ubuntu-latest
    needs: build
    # Only create a release on a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: ncipollo/release-action@v1
        with:
          name: "JA2 Stracciatella ${{ github.ref_name }}"
          artifacts: "./artifacts/*/*.flatpak"
          token: ${{ secrets.GITHUB_TOKEN }}
