name: 'Build image for merge workflow'

on:
  push:
    branches: master
    paths:
      - ".github/actions/merge/*"
      - .github/workflows/merge.yml
      - .github/workflows/build-merge.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        # 3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to ghcr.io
        # 3.4.0
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        # 6.15.0
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .github/actions/merge
          file: .github/actions/merge/Dockerfile
          tags: ghcr.io/flathub/actions/merge:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
