name: CI

on:
  push:
    branches: [meshtasticd]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: meshtasticd.flatpak
        manifest-path: org.meshtastic.meshtasticd.yaml
        cache-key: flatpak-builder-${{ github.sha }}
