name: Close PRs to master

# DO NOT RUN ANY CODE OR CHECKOUT OR USE ORG SECRETS HERE
# pull_request_target RUNS ON PUBLIC FORKS IN REPO'S CONTEXT

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
    branches:
      - master
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Check and close
        run: |
          has_label=$(gh pr --repo "$REPO" view "${{ github.event.pull_request.number }}" --json labels -q '.labels | any(.name == "leave-open")')
          if [[ "$has_label" != "true" ]]; then
              echo "leave-open label not found. Closing."
              gh pr --repo "$REPO" close "${{ github.event.pull_request.number }}" -c "$COMMENT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: flathub/flathub
          COMMENT: >
              This PR is automatically closed because application submission
              PRs must be made against the new-pr branch. If this is done
              in error, please comment.
              ![PR Image](https://raw.githubusercontent.com/flathub/flathub/refs/heads/master/.github/images/pr_image.png)
