name: Label quality guidelines issues

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  label:
    if: startsWith(github.event.issue.title, 'Quality guideline problems for')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label
        run: gh issue edit "${{ github.event.issue.number }}" --add-label "quality-guidelines"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
