name: "Lock closed PRs"

on:
  schedule:
  - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install -y jq

      - name: Lock closed PRs
        run: |
          cmd=$(gh pr list --repo "$REPO" -L 100 --state closed --json number,updatedAt|jq '[.[] | select(.updatedAt >= (now - (7 * 24 * 60 * 60) | todate))] | sort_by(.updatedAt) | .[] | {number: .number, updatedAt: .updatedAt}'| jq '.number')

          for num in $cmd; do
            if [ "$(gh api repos/$REPO/issues/$num --jq '.active_lock_reason'| wc -c)" -le 1 ]; then
              gh pr lock --repo "$REPO" --reason "resolved" "$num"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
          REPO: flathub/flathub
