name: Update commit hash
on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00

jobs:
  change-commit:
    name: Change the commit hash to the latest upstream one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change commit
        run: |
          build_tag=$(git ls-remote https://github.com/mborgerson/xemu 'refs/tags/build-*' | awk -F/ 'END { print $NF }')
          sed -i "s/  tag: .*/  tag: $build_tag/" app.xemu.xemu.yml
          date=${build_tag#build-}
          year_month_day=$(date -I -d ${date%????})
          sed -i "s|    <release .*|    <release date=\"$year_month_day\" version=\"$build_tag\" />|" app.xemu.xemu.metainfo.xml
      - name: Push the change
        run: |
          git config user.name CI
          git config user.email ""
          git add app.xemu.xemu.yml
          git commit -m "Update xemu.git" || exit 0
          git push
