name: Check PRs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  issue_comment:
    types: [created]

jobs:
  check-prs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      pull-requests: write
    steps:
      - if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/review')
        # 0.1.4
        uses: flathub-infra/flathub-submission-checker@aa83471e9bd8bbfee8578f8b53e2a79d9ba0ea0f
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          PR_NUMBER: ${{ github.event.issue.number }}

      - if: github.event_name != 'issue_comment'
        # 0.1.4
        uses: flathub-infra/flathub-submission-checker@aa83471e9bd8bbfee8578f8b53e2a79d9ba0ea0f
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
