name: Check PRs
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to review'
        required: true
        type: string
  schedule:
    - cron: '0 */2 * * *'
  issue_comment:
    types: [created]

jobs:
  check-prs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      pull-requests: write
    steps:
      - if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/review')
        uses: flathub-infra/flathub-submission-checker@b346b2c6633e149512bb46269ad1f8f10f70ef90
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          PR_NUMBER: ${{ github.event.issue.number }}

      - if: github.event_name == 'workflow_dispatch'
        uses: flathub-infra/flathub-submission-checker@b346b2c6633e149512bb46269ad1f8f10f70ef90
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMENT_BODY: /review
          PR_NUMBER: ${{ inputs.pr_number }}

      - if: github.event_name == 'schedule'
        uses: flathub-infra/flathub-submission-checker@b346b2c6633e149512bb46269ad1f8f10f70ef90
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
