name: 'Publish flatpak to Github releases'
on:
  push:
    tags: v*
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
        manifest-path: io.github.ja2_stracciatella.JA2-Stracciatella.yaml
    - uses: actions/upload-artifact@v3
      with:
        name: io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
        path: ./io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: ncipollo/release-action@v1
        with:
          name: 'JA2 Stracciatella ${{ github.ref_name }}'
          artifacts: "./artifacts/*/*.flatpak"
          token: ${{ secrets.GITHUB_TOKEN }}
