name: "Close stale blocked PRs"
on:
  schedule:
  - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  stale:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # 9.1.0
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: |-
          This pull request has not received any updates and it will be
          automatically closed in 7 days. Please comment or reopen if
          necessary.
        days-before-stale: -1
        days-before-close: -1
        days-before-pr-stale: 23
        days-before-pr-close: 7
        any-of-pr-labels: blocked,pr-check-blocked
        remove-stale-when-updated: false
        exempt-pr-labels: leave-open
        operations-per-run: 200
        ascending: true
        ignore-updates: true
