name: Label and tag quality mod team

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:

jobs:
  label_and_tag:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: startsWith(github.event.issue.title, 'Quality guideline problems for')
    steps:
      - name: Label
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: quality-guidelines

      - name: Add comment tagging the team
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.FLATHUBBOT_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening this issue! cc @flathub/quality-moderation
