name: Tag quality mod team

on:
  issues:
    types: [labeled]
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'quality-guidelines' && startsWith(github.event.issue.title, 'Quality guideline problems for')
    steps:
      - name: Add comment tagging the team
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.FLATHUBBOT_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening this issue! cc @flathub/quality-moderation
