name: 'Test flatpak build'
on:
  push:
jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: io.github.ja2-stracciatella.flatpak
        manifest-path: io.github.ja2-stracciatella.yml
