name: 'Test flatpak build'
on:
  push:
jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
        manifest-path: io.github.ja2_stracciatella.JA2-Stracciatella.yaml
    - uses: actions/upload-artifact@v3
      with:
        name: io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
        path: ./io.github.ja2_stracciatella.JA2-Stracciatella.flatpak
